function SPEC_DATA(L){const {M,R,C,G,T,H,I,btn,badge,count,box,note,lbl,J,esc,avatar,avGroup,pc,stb,field,check,seg,menu,pop,chip,kv,list,listRow,spin,skel,kbd,table,stat,spark,money,pager,empty,alert,kcard,kcol,kgap,board,prog,phoneMini,PEOPLE}=L;
const P=PEOPLE;
const cols=[{l:'Name',w:'minmax(200px,2fr)'},{l:'Team'},{l:'Location'},{l:'Status',w:'128px'},{l:'Start date',w:'112px',m:1}];
const rows=P.map(p=>[pc(p),p.t,p.l,stb(p.s),p.d]);
const tb=(extra='')=>R([field({pre:'i:search',ph:'Search people',size:'sm',w:M?undefined:240,flex:M?'1 1 100%':undefined}),chip('Engineering',{k:'Team',remove:1,on:1}),chip('Filter',{icon:'plus',dashed:1})],{gap:8})+`<span style="margin-left: auto; display: flex; gap: 8px;">${extra}</span>`;
const moneyCols=[{l:'Name',w:'minmax(180px,2fr)'},{l:'Team'},{l:'FTE',a:'r',w:'60px'},{l:'Base salary',a:'r',w:'120px'},{l:'Bonus',a:'r',w:'100px'},{l:'Change',a:'r',w:'90px'}];
const moneyRows=P.slice(0,6).map((p,i)=>[pc(p),p.t,[1,1,0.8,1,0.6,1][i].toFixed(1),money(p.sal),money([4600,8000,0,3550,1200,0][i]),`<span style="color: ${[1,1,0,1,-1,0][i]>0?'var(--r-success-text)':[1,1,0,1,-1,0][i]<0?'var(--r-danger-text)':'var(--r-fg-3)'};">${['+4.5%','+6.0%','—','+3.0%','−2.0%','—'][i]}</span>`]);
const vrows=(start,n,o={})=>Array.from({length:n},(_,k)=>{const i=start+k;const p=P[i%P.length];return [`<span style="font: 500 12px/1 var(--r-mono); color: var(--r-fg-3); width: 54px; flex: none;">#${(i+1).toLocaleString('en-GB')}</span>${pc(p,{sub:p.t})}`,p.l,stb(p.s),p.d];});
const vcols=[{l:'Person',w:'minmax(240px,2fr)',sort:true},{l:'Location'},{l:'Status',w:'128px'},{l:'Start date',w:'112px',m:1}];
const cand=[['Hana Kim','Product Designer',['Portfolio']],['Leo Rossi','Backend Engineer',['Referral']],['Ines Duarte','Account Executive',[]],['Ravi Patel','Data Analyst',['Remote']],['Maya Cohen','iOS Engineer',['Senior']],['Sam Okoro','Support Lead',[]],['Eva Novak','Recruiter',['Internal']],['Ali Rahman','Designer',[]]];
const kc=(i,o={})=>{const [n,r,tags]=cand[i%cand.length];return kcard({t:n,tags:`<span style="font: 400 13px/1.3 var(--r-font); color: var(--r-fg-2);">${r}</span>${tags.map(t=>badge(t,{size:'sm'})).join('')}`,av:o.av||[P[i%5].n],handle:o.handle,menu:o.menu,drag:o.drag,focus:o.focus,check:o.check,locked:o.locked});};
const col=(t,n,cards,o={})=>kcol({t,n,cards,dot:o.dot,over:o.over,locked:o.locked,add:o.add,drop:o.drop,h:o.h,w:o.w});
const stages=[['Applied','var(--r-fg-3)'],['Screen','var(--r-info)'],['Interview','var(--r-accent)'],['Offer','var(--r-warning)'],['Hired','var(--r-success)']];
const std=(o={})=>board(stages.map(([s,d],si)=>col(s,[5,3,4,2,6][si],[0,1,2].slice(0,[3,2,3,1,2][si]).map(k=>kc(si*2+k,o)),{dot:d,add:si===0})));
const cond=(f,op,v,o={})=>M?`<div style="padding: 12px; border-radius: 16px; background: var(--r-fill); display: flex; flex-direction: column; gap: 8px;">${o.join?`<span style="font: 600 12px/1 var(--r-font); color: var(--r-fg-2);">${o.join}</span>`:''}${field({value:f,suf:'i:chevron-down',size:'sm'})}${field({value:op,suf:'i:chevron-down',size:'sm'})}${R([`<div style="flex: 1;">${field({value:v,ph:'Value',size:'sm',state:o.err?'error':undefined})}</div>`,btn('',{v:'ghost',size:'xs',icon:'trash-2'})],{gap:6,nowrap:1})}</div>`:`<div style="display: grid; grid-template-columns: 64px 1fr 1fr 1.3fr 32px; gap: 8px; align-items: center;"><span style="font: 600 13px/1 var(--r-font); color: var(--r-fg-2); text-align: right;">${esc(o.join||'Where')}</span>${field({value:f,suf:'i:chevron-down',size:'sm'})}${field({value:op,suf:'i:chevron-down',size:'sm'})}${field({value:v,ph:'Value',size:'sm',state:o.err?'error':undefined})}${btn('',{v:'ghost',size:'xs',icon:'x'})}</div>`;
const fb=(conds,o={})=>box(C([R([H('Filters',{s:M?18:16}),o.any?seg(['All','Any'],1,{size:'sm'}):'',`<span style="margin-left: auto;">${btn('Clear',{v:'ghost',size:'sm'})}</span>`],{gap:10}),...conds,R([btn('Add condition',{v:'secondary',size:'sm',icon:'plus'}),`<span style="margin-left: auto;">${btn(o.cta||'Show 48 people',{size:'sm'})}</span>`],{gap:8})],{gap:10}));
const sortRow=(t,s,o={})=>`<div style="display: flex; align-items: center; gap: 12px; min-height: ${M?60:52}px; padding: 8px ${M?14:16}px; box-sizing: border-box; border-radius: 14px; background: ${o.drag?'var(--r-surface-raised)':'var(--r-surface)'}; box-shadow: ${o.drag?'var(--r-shadow-4)':o.gap?'none':'var(--r-shadow-1)'};${o.drag?' transform: rotate(-1deg) scale(1.02);':''}${o.gap?' border: 1.5px dashed var(--r-accent); background: var(--r-accent-soft);':''}${o.locked?' opacity: 0.7;':''}${o.whole?' cursor: grab;':''}">${o.gap?'':`${o.locked?I('lock',16,'var(--r-fg-3)'):o.whole?'':I('grip-vertical',16,'var(--r-fg-3)')}${o.lead||''}<div style="flex: 1; min-width: 0;"><div style="font: 600 ${M?16:14}px/1.3 var(--r-font);">${esc(t)}</div>${s?`<div style="font: 400 ${M?14:13}px/1.3 var(--r-font); color: var(--r-fg-2);">${esc(s)}</div>`:''}</div>${o.trail||''}`}</div>`;
const S=[];
S.push({g:'Data',id:'table',name:'Table',desc:M?'On a phone, each row becomes a card. The first column is the title, the key values sit underneath it, and tapping the card opens the detail.':'Rows of records. Names come first and are the boldest thing in the row. Numbers align right with tabular figures.',stories:[
['Directory',table({cols,rows:rows.slice(0,6),mHide:[4]}),{wide:1}],
['Numeric alignment',table({cols:moneyCols,rows:moneyRows,mRight:3,mLabels:true,footer:`<span>Totals</span><span style="font: 600 13px/1 var(--r-font); color: var(--r-fg); font-variant-numeric: tabular-nums;">${money(521000,'EUR','en-GB',{plain:1})} · ${money(17350,'EUR','en-GB',{plain:1})}</span>`}),{wide:1,note:'Right-align numbers and money, and use the same number of decimals down the whole column.'}],
['Interactive rows',table({cols,rows:rows.slice(0,5),hover:1,hoverable:1,focusRow:3,mHide:[4]}),{wide:1,note:M?'The whole card is tappable, and the chevron shows it opens something.':'Hover tints the row, and a click opens the record. Focus shows a ring, and Enter opens.'}],
['Loading',table({cols,rows:[],loading:6}),{wide:1}],
['Empty',table({toolbar:tb(),cols,rows:[],empty:empty({icon:'search-x',title:'No one matches "Priyaa"',body:'Check the spelling, or clear the Engineering filter.',acts:btn('Clear filters',{v:'secondary',size:'sm'})})}),{wide:1}],
['DataTable: expandable rows',table({cols,rows:rows.slice(0,5),expand:1,expanded:1,expHtml:`<div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(160px, 1fr)); gap: 16px;">${kv([['Manager','Nora Becker'],['Reports','6 people']],{stack:1})}${kv([['Email','jonas@reach.co'],['Phone','+49 151 000 1122']],{stack:1})}</div>`,mHide:[4]}),{wide:1}],
['DataTable: selection and bulk actions',table({cols,rows:rows.slice(0,6),select:1,sel:[0,2,3],allSel:'mixed',bulk:'3 selected',mHide:[4]}),{wide:1}],
['DataTable: sorting',table({cols:[{l:'Name',w:'minmax(200px,2fr)',sort:true},{l:'Team',sort:'asc',pri:'1'},{l:'Location',sort:true},{l:'Status',w:'128px'},{l:'Start date',w:'112px',sort:'desc',pri:'2',m:1}],rows:[1,0,8,9,2,3].map(i=>rows[i]),sortLabel:'Team, then start date',mHide:[4]}),{wide:1,note:'Click to sort, click again to reverse. Shift-click adds a second sort, and the small numbers show the order.'}],
['DataTable: drag to reorder',table({cols:[{l:'Priority',w:'minmax(200px,2fr)'},{l:'Owner',w:'minmax(160px,1fr)'},{l:'Due',w:'110px'}],rows:[['Renew Berlin office lease',pc(P[7],{s:28,sub:'People'}),'30 Sep'],['Q4 salary review',pc(P[11],{s:28,sub:'Finance'}),'15 Oct'],['Launch mentoring',pc(P[6],{s:28,sub:'People'}),'1 Nov'],['Migrate payroll',pc(P[1],{s:28,sub:'Engineering'}),'1 Dec']],drag:1,dragging:1,gap:3}),{wide:1}],
['DataTable, all of it at once',table({toolbar:tb(`${btn('Columns',{v:'secondary',size:'sm',icon:'columns-3'})}${btn('Export',{v:'secondary',size:'sm',icon:'download'})}`),cols:[{l:'Name',w:'minmax(200px,2fr)',sort:'asc'},{l:'Team',sort:true},{l:'Location'},{l:'Status',w:'128px'},{l:'Start date',w:'112px',sort:true,m:1}],rows:rows.slice(0,6),select:1,sel:[1,4],allSel:'mixed',expand:1,expanded:4,expHtml:note('Mei Tanaka · Data Analyst · reports to Zara Ahmed'),sticky:1,resize:1,bulk:'2 selected',footer:`<span>Showing 1–6 of 312</span>${pager([1,2,3,'…',52],1)}`,mFooter:pager([1,2],1,{total:52}),mHide:[4]}),{wide:1}],
['DataTable, on a phone',M?table({toolbar:R([field({pre:'i:search',ph:'Search',size:'sm'})],{style:' width: 100%;'}),cols,rows:rows.slice(0,5),select:1,sel:[1],bulk:'1 selected',mHide:[4]}):R([phoneMini(C([T('People',{s:22,w:700,d:1}),field({pre:'i:search',ph:'Search',size:'sm'}),list(P.slice(0,5).map((p,i,a)=>`<div style="display: flex; gap: 10px; padding: 10px 12px; ${i<a.length-1?'box-shadow: inset 0 -1px 0 var(--r-line);':''}">${check(i===1?'on':'off')}<div style="flex: 1; min-width: 0;">${pc(p,{s:28})}<div style="margin-top: 6px; display: flex; gap: 8px; align-items: center; font: 400 12px/1 var(--r-font); color: var(--r-fg-2);">${p.t}${stb(p.s)}</div></div></div>`))],{gap:10}),{h:520}),`<div style="flex: 1 1 240px;">${note('Every column is still there, stacked under the name. Selection moves to a leading checkbox, and bulk actions go in a bar at the bottom.')}</div>`],{gap:24}),{wide:1}],
['Virtualized',table({cols:vcols,rows:vrows(18200,10),scrollH:360,sticky:1,footer:`<span>Rendering 24 of 20,000 rows</span><span style="font-family: var(--r-mono);">row 18,201</span>`,mFooter:'<span>Rendering 12 of 20,000</span>'}),{wide:1}],
['Infinite, striped, resizable',table({cols:[{l:'Name',w:'minmax(200px,2fr)'},{l:'Team',resizing:1},{l:'Location'},{l:'Status',w:'128px'}],rows:rows.slice(0,6).map(r=>r.slice(0,4)),striped:1,resize:1,after:`<div style="height: 48px; display: flex; align-items: center; justify-content: center; gap: 10px; font: 500 13px/1 var(--r-font); color: var(--r-fg-2);">${spin(16)}Loading more</div>`,mAfter:`<div style="height: 52px; display: flex; align-items: center; justify-content: center; gap: 10px; font: 500 14px/1 var(--r-font); color: var(--r-fg-2);">${spin(16)}Loading more</div>`}),{wide:1}],
['Grouped',table({cols:moneyCols.slice(0,4),rows:[],groups:[{l:'Engineering',n:4,off:0,sum:money(388000,'EUR','en-GB',{plain:1}),rows:[0,1,8,9].map(i=>[pc(P[i]),P[i].l,'1.0',money(P[i].sal)])},{l:'Design',n:1,off:4,sum:money(84000,'EUR','en-GB',{plain:1}),rows:[[pc(P[2]),P[2].l,'0.8',money(84000)]]},{l:'Sales',n:2,open:false,off:5,rows:[]}],mRight:3}),{wide:1}],
['Virtualized, sorted',table({cols:[{l:'Person',w:'minmax(240px,2fr)',sort:'asc'},{l:'Location'},{l:'Status',w:'128px'},{l:'Start date',w:'112px',m:1}],rows:vrows(0,8),scrollH:320,sticky:1,sortLabel:'Name A–Z',footer:'<span>Sorted 20,000 rows on the server in 180 ms</span>'}),{wide:1}],
['Virtualized, selection',table({cols:vcols,rows:vrows(4000,8),select:1,sel:[0,1,2,3,4,5,6,7],allSel:'on',scrollH:320,sticky:1,bulk:'All 20,000 selected',bulkActs:['Export','Message'],footer:'<span>Select all picks every row that matches, not just the rows on screen.</span>'}),{wide:1}],
['Virtualization off',C([alert({tone:'info',title:'Under 200 rows? Don\u2019t virtualize.',body:'Plain rows let ⌘F, printing and screen readers work properly.'}),table({cols,rows:rows.slice(0,4),footer:'<span>All 4 rows rendered</span>',mHide:[4]})],{gap:10}),{wide:1}]]});
S.push({g:'Data',id:'column-chooser',name:'ColumnChooser',desc:'Lets people pick and reorder table columns. Their choice is saved for each table.',stories:[
['Playground',pop(C([R([T('Columns',{w:600}),`<span style="margin-left: auto; font: 500 12px/1 var(--r-font); color: var(--r-fg-2);">5 of 8</span>`]),field({pre:'i:search',ph:'Find a column',size:'sm'}),...[['Name',1,1],['Team',1],['Location',1],['Status',1],['Start date',1],['Manager',0],['Salary',0],['Employee ID',0]].map(([c,on,lock])=>`<div style="display: flex; align-items: center; gap: 10px; min-height: ${M?44:32}px;">${I(lock?'lock':'grip-vertical',15,'var(--r-fg-3)')}${check(on?'on':'off',c,{disabled:lock})}</div>`),`<div style="display: flex; justify-content: space-between; margin-top: 6px;">${btn('Reset',{v:'ghost',size:'sm'})}${btn('Done',{size:'sm'})}</div>`],{gap:4}),{w:280})],
['Driving a table',C([R([btn('Columns',{v:'tinted',size:'sm',icon:'columns-3',count:3})],{justify:'flex-end'}),table({cols:[{l:'Name',w:'minmax(200px,2fr)'},{l:'Team'},{l:'Manager'}],rows:P.slice(0,4).map((p,i)=>[pc(p),p.t,['Jonas Weber','Nora Becker','Jonas Weber','Tom Fischer'][i]]),minW:420})],{gap:8}),{wide:1}]]});
S.push({g:'Data',id:'filter-builder',name:'FilterBuilder',desc:'Build filters out of conditions. Applied filters then show as chips above the results.',stories:[
['Playground',fb([cond('Team','is','Engineering'),cond('Start date','is after','1 Jan 2024',{join:'and'})]),{wide:!M}],
['Nothing yet',box(empty({icon:'filter',title:'No filters yet',body:'Add a condition to narrow down 312 people.',acts:btn('Add condition',{v:'secondary',size:'sm',icon:'plus'}),pad:10}))],
['Any condition',fb([cond('Location','is','Berlin'),cond('Location','is','Remote',{join:'or'}),cond('Salary','is above','',{join:'or',err:1})],{any:1,cta:'Show 96 people'}),{wide:!M}],
['Applied, as removable chips',C([R([chip('Engineering',{k:'Team',remove:1,on:1}),chip('after 1 Jan 2024',{k:'Start',remove:1,on:1}),chip('Berlin or Remote',{k:'Location',remove:1,on:1}),btn('Clear all',{v:'ghost',size:'sm'})],{gap:8}),note('48 people match')])]]});
S.push({g:'Data',id:'kanban',name:'Kanban',desc:'Move work between stages. Drag with a mouse or a finger, or use the keyboard or the card menu. Every drag has a non-drag alternative.',stories:[
['Playground',std({handle:'left'}),{wide:1}],
['Without a mouse',C([board([col('Applied',3,[kc(0,{focus:1}),kc(1)]),col('Screen',2,[kc(2),kc(3)])]),`<div style="display: flex; gap: 12px; flex-wrap: wrap; font: 400 13px/1 var(--r-font); color: var(--r-fg-2);"><span>${kbd('Space')} pick up</span><span>${kbd(['←','→'])} move column</span><span>${kbd(['↑','↓'])} move in column</span><span>${kbd('Esc')} cancel</span></div>`,`<div role="status" style="font: 500 13px/1.4 var(--r-font); color: var(--r-fg-2); padding: 10px 12px; border-radius: 10px; background: var(--r-fill);">Hana Kim picked up. Position 1 of 3 in Applied.</div>`],{gap:12}),{wide:1}],
['Limits and locked columns',board([col('Interview',"4 / 4",[kc(4),kc(5),kc(6),kc(7)],{over:1,dot:'var(--r-accent)'}),col('Offer','2 / 3',[kc(0),kc(1)],{dot:'var(--r-warning)'}),col('Hired','6',[kc(2,{locked:1}),kc(3,{locked:1})],{locked:1,dot:'var(--r-success)'})]),{wide:1,note:'A full column refuses drops and says why. A locked column still shows its cards, but you can\u2019t move them.'}],
['The gap opens in both columns',board([col('Screen',2,[kc(0),kgap(),kc(1)],{dot:'var(--r-info)'}),col('Interview',4,[kc(2),`<div style="height: 8px;"></div>`,kc(3,{drag:1}),kc(4)],{dot:'var(--r-accent)',drop:1})]),{wide:1,note:'The card\u2019s old spot stays open until you drop it, so there\u2019s always a clear way back.'}],
['On a phone',M?C([seg(['Applied 5','Screen 3','Interview 4'],1,{full:1,size:'sm'}),col('Screen',3,[kc(2,{menu:1}),kc(3,{menu:1}),kc(4,{menu:1})],{w:358,dot:'var(--r-info)'}),note('One column at a time. Swipe or use the segmented control to switch. Long-press to drag.')],{gap:10}):R([phoneMini(C([seg(['Applied','Screen','Interview'],1,{full:1,size:'sm'}),C([kc(2,{menu:1}),kc(3,{menu:1}),kc(4,{menu:1})],{gap:8})],{gap:10}),{h:480}),`<div style="flex: 1 1 240px;">${note('One column at a time, switched with a segmented control. Long-press starts a drag, and the ⋯ menu offers "Move to…".')}</div>`],{gap:24}),{wide:1}],
['Handle positions',R([C([lbl('Left handle'),kc(0,{handle:'left'})],{gap:6,style:' flex: 1 1 200px;'}),C([lbl('Right handle'),kc(1,{handle:'right'})],{gap:6,style:' flex: 1 1 200px;'}),C([lbl('No handle'),kc(2)],{gap:6,style:' flex: 1 1 200px;'})],{gap:12,align:'flex-start'})],
['The whole card drags',C([kc(3,{drag:1}),note('Without a handle, the whole card is the drag target. Links and buttons inside it still work.')],{gap:12})],
['Scroll speed and motion',C([`<div style="position: relative;">${board([col('Applied',5,[kc(0),kc(1)]),col('Screen',3,[kc(2)]),col('Interview',4,[kc(3)])])}<span style="position: absolute; top: 0; bottom: 0; right: 0; width: 60px; background: linear-gradient(90deg, transparent, color-mix(in oklch, var(--r-accent) 18%, transparent)); border-radius: 0 18px 18px 0; display: grid; place-items: center; color: var(--r-accent-text);">${I('chevrons-right',20)}</span></div>`,note('Near an edge, the board scrolls faster the closer you get. Under reduced motion, cards snap into place without gliding.')],{gap:10}),{wide:1}],
['Menu only',R([kc(0,{menu:1}),menu([{l:'Move to',icon:'arrow-right-left',sub:1},{l:'Move to top',icon:'arrow-up-to-line'},{l:'Move to bottom',icon:'arrow-down-to-line'},'-',{l:'Remove',icon:'trash-2',danger:1}],{w:220})],{gap:8,align:'flex-start'})],
['Card and bulk actions',C([board([col('Applied',5,[kc(0,{check:true}),kc(1,{check:true}),kc(2,{check:false})]),col('Screen',3,[kc(3,{check:false})])]),`<div style="display: flex; align-items: center; gap: 6px; padding: 6px 6px 6px 18px; background: var(--r-invert); color: var(--r-on-invert); border-radius: 999px; box-shadow: var(--r-shadow-3); font: 600 14px/1 var(--r-font); align-self: center;">2 selected<span style="width: 1px; height: 20px; background: color-mix(in oklch, var(--r-on-invert) 25%, transparent); margin: 0 8px;"></span><span style="height: 32px; padding: 0 12px; border-radius: 999px; display: inline-flex; align-items: center; background: color-mix(in oklch, var(--r-on-invert) 12%, transparent);">Move to Screen</span><span style="height: 32px; padding: 0 12px; border-radius: 999px; display: inline-flex; align-items: center; background: color-mix(in oklch, var(--r-on-invert) 12%, transparent);">Reject</span></div>`],{gap:12}),{wide:1}],
['Adding and deleting sections',board([col('Applied',2,[kc(0)]),col('Screen',1,[kc(1)]),`<div style="flex: none; width: ${M?300:260}px; border-radius: 18px; border: 1.5px dashed var(--r-line-strong); padding: 12px; display: flex; flex-direction: column; gap: 10px; box-sizing: border-box;">${field({value:'Take-home task',state:'focus',size:'sm'})}<div style="display: flex; gap: 6px;">${btn('Add section',{size:'sm'})}${btn('Cancel',{v:'ghost',size:'sm'})}</div></div>`]),{wide:1,note:'Deleting a section that has cards asks where to move them first.'}],
['A very long column',board([col('Applied',48,[0,1,2,3,4].map(i=>kc(i)).concat([`<span style="text-align: center; font: 600 13px/1 var(--r-font); color: var(--r-fg-2); padding: 8px;">+ 43 more</span>`]),{h:M?520:460}),col('Screen',2,[kc(5),kc(6)])]),{wide:1}],
['Every column long',board(stages.slice(0,4).map(([s,d],si)=>col(s,[48,36,22,12][si],[0,1,2,3].map(k=>kc(si+k)),{dot:d,h:M?460:400}))),{wide:1,note:'Each column scrolls on its own, and the headers stay in place.'}],
['Just below the threshold',C([board([col('Screen',2,[kc(0),kc(1,{drag:1})])]),note('Nothing moves until the pointer travels 6px (or you long-press for 250ms on touch), so clicks and scrolls are never mistaken for drags.')],{gap:10})]]});
S.push({g:'Data',id:'key-values',name:'KeyValues',desc:'Label and value pairs for record details. Keys are quiet and values are clear.',stories:[
['Default',kv([['Team','Engineering'],['Manager','Jonas Weber'],['Location','Berlin'],['Start date','2 Sep 2024']])],
['In A Card',box(C([R([H('Employment'),`<span style="margin-left: auto;">${btn('Edit',{v:'ghost',size:'sm',icon:'pencil'})}</span>`]),kv([['Contract','Permanent'],['Hours','40 per week'],['Notice','3 months']])],{gap:8}))],
['Rich Values',kv([['Manager',R([avatar('Jonas Weber',{size:24}),T('Jonas Weber',{w:500,s:M?16:14})],{gap:8}),1],['Status',stb('Active'),1],['Email',`<a href="#">priya@reach.co</a>`,1],['Skills',R(['React','TypeScript','Figma'].map(s=>badge(s,{size:'sm'})),{gap:4}),1],['Salary',`<span style="display: inline-flex; gap: 6px; align-items: center;">${badge('Private',{icon:'lock',size:'sm'})}${money(92000)}</span>`,1]])]]});
S.push({g:'Data',id:'money',name:'Money',desc:'Money stays exact. It\u2019s stored in minor units, formatted for the locale, and always shown with its currency.',stories:[
['Playground',T(money(4280,'EUR','en-GB',{plain:1}),{s:M?34:32,w:700,d:1,num:1,ls:'-0.02em'})],
['Currencies',C([['EUR','en-GB',4280],['GBP','en-GB',3650],['USD','en-US',5120],['JPY','ja-JP',612000],['CHF','de-CH',6400.5]].map(([c,l,v])=>`<div style="display: flex; justify-content: space-between; font: 500 ${M?17:15}px/1 var(--r-font);"><span style="color: var(--r-fg-2);">${c}</span>${money(v,c,l,{dp:c==='JPY'?0:2})}</div>`),{gap:12})],
['Precision a double would lose',C([`<div style="display: flex; justify-content: space-between; font: 500 14px/1 var(--r-font);"><span style="color: var(--r-fg-2);">0.1 + 0.2 as floats</span><span style="font-family: var(--r-mono); color: var(--r-danger-text);">0.30000000000000004</span></div>`,`<div style="display: flex; justify-content: space-between; font: 500 14px/1 var(--r-font);"><span style="color: var(--r-fg-2);">10 + 20 cents</span><span style="font-family: var(--r-mono); color: var(--r-success-text);">€0.30</span></div>`,`<div style="display: flex; justify-content: space-between; font: 500 14px/1 var(--r-font);"><span style="color: var(--r-fg-2);">Payroll total</span>${money(9007199254740.99,'EUR','en-GB')}</div>`],{gap:14})],
['Negative',C([R([T('Refund',{c:'var(--r-fg-2)'}),`<span style="margin-left: auto; font: 600 ${M?17:15}px/1 var(--r-font);">${money(-86)}</span>`]),R([T('Overpayment',{c:'var(--r-fg-2)'}),`<span style="margin-left: auto; font: 600 ${M?17:15}px/1 var(--r-font);">${money(-1240.5,'EUR','en-GB',{tone:1})}</span>`]),R([T('Accounting',{c:'var(--r-fg-2)'}),`<span style="margin-left: auto; font: 600 ${M?17:15}px/1 var(--r-font); font-variant-numeric: tabular-nums;">(€1,240.50)</span>`]),note('Use a true minus sign. Red is only for amounts that are genuinely a problem.')],{gap:12})],
['Locales',C([['en-GB','English (UK)'],['de-DE','Deutsch'],['fr-FR','Français'],['ja-JP','日本語']].map(([l,n])=>`<div style="display: flex; justify-content: space-between; font: 500 ${M?16:14}px/1 var(--r-font);"><span style="color: var(--r-fg-2);">${n}</span>${money(92000.5,'EUR',l)}</div>`),{gap:12})],
['In a column',table({cols:[{l:'Payslip',w:'minmax(140px,1fr)'},{l:'Gross',a:'r',w:'120px'},{l:'Net',a:'r',w:'120px'}],rows:[['September',money(7666.67),money(4280)],['August',money(7666.67),money(4280)],['July (bonus)',money(12266.67),money(6912.4)],['June',money(7250),money(4050)]],mRight:2,mLabels:true,minW:380})]]});
S.push({g:'Navigation',id:'pagination',name:'Pagination',desc:M?'On a phone, pagination is "Page 3 of 52" between two arrows. Lists usually load more as you scroll instead.':'Move through pages of results. The current page is filled, and the gaps collapse into an ellipsis.',stories:[
['Playground',pager([1,2,3,4,5],3,{full:!M,total:5})],
['How the window elides',C([pager([1,2,3,4,5,'…',52],2,{full:1}),pager([1,'…',24,25,26,'…',52],25,{full:1}),pager([1,'…',48,49,50,51,52],51,{full:1})],{gap:10})],
['Few enough not to elide',pager([1,2,3,4,5,6,7],4,{full:1})],
['Under a table',table({cols:cols.slice(0,3),rows:rows.slice(0,3).map(r=>r.slice(0,3)),footer:`<span>21–30 of 312</span>${pager([1,2,3,'…',32],3)}`,mFooter:pager([1,2,3],3,{total:32}),minW:420}),{wide:1}]]});
S.push({g:'Data',id:'sortable-list',name:'SortableList',desc:'Reorder a short list by dragging. Keyboard and screen readers are supported, and every move is announced.',stories:[
['Playground',C([sortRow('Payroll','Monthly'),sortRow('Time off','Always'),sortRow('Insights','Weekly'),sortRow('Documents','Rarely')],{gap:8})],
['A row that cannot move',C([sortRow('Home','Always first',{locked:1}),sortRow('People',''),sortRow('Time off',''),sortRow('Payroll','')],{gap:8})],
['Dragging the whole row',C([sortRow('Payroll','',{whole:1}),sortRow('Time off','',{whole:1,drag:1}),sortRow('','',{gap:1}),sortRow('Insights','',{whole:1})],{gap:8})],
['Rows that say what they are',C(P.slice(0,4).map((p,i)=>sortRow(p.n,`Approver ${i+1}`,{lead:avatar(p.n,{size:32}),trail:`<span style="font: 600 12px/1 var(--r-font); color: var(--r-fg-3);">${i+1}</span>`})).concat([`<div role="status" style="font: 500 13px/1.4 var(--r-font); color: var(--r-fg-2);">Screen reader: "Jonas Weber, approver 2 of 4. Moved to position 1."</div>`]),{gap:8})]]});
S.push({g:'Data',id:'stat',name:'Stat',desc:'One number with context. Direction and sentiment are separate: fewer leavers is down, and that\u2019s good.',stories:[
['Playground',stat({l:'Headcount',v:'312',d:'+12 this quarter',good:true})],
['Direction is not sentiment',G([stat({l:'Attrition',v:'6.1',u:'%',d:'0.8 pts lower',dir:'down',good:true}),stat({l:'Open roles',v:'18',d:'4 more',dir:'up',good:false}),stat({l:'Avg. tenure',v:'2.4',u:'yrs',d:'No change',dir:'flat',good:null})],M?150:180)],
['With money',G([stat({l:'Payroll, September',v:money(1284300,'EUR','en-GB',{dp:0,plain:1}),d:'+2.1% on August',good:null}),stat({l:'Unclaimed expenses',v:money(3480,'EUR','en-GB',{dp:0,plain:1}),d:'14 people',good:false,dir:'up'})],M?150:200)],
['With a sparkline',G([stat({l:'Headcount',v:'312',d:'+18.6% YoY',good:true,spark:[263,266,271,274,279,285,289,294,297,301,306,312]}),stat({l:'Time to hire',v:'24',u:'days',d:'3 faster',dir:'down',good:true,spark:[31,30,29,29,27,26,25,24]})],M?150:200)],
['In a narrow column',`<div style="width: ${M?'100%':'220px'}; display: flex; flex-direction: column; gap: 10px;">${stat({l:'Headcount',v:'312',d:'+12',good:true,narrow:1,size:28})}${stat({l:'Leavers',v:'4',d:'−2',dir:'down',good:true,size:28})}</div>`]]});
S.push({g:'Data',id:'virtual-list',name:'VirtualList',desc:'Renders only the rows you can see, so 20,000 rows scroll smoothly. Row heights can vary.',stories:[
['Twenty Thousand',C([list(Array.from({length:8},(_,k)=>{const i=12480+k,p=P[i%P.length];return listRow({lead:`<span style="font: 500 11px/1 var(--r-mono); color: var(--r-fg-3); width: 48px;">#${(i+1).toLocaleString('en-GB')}</span>${avatar(p.n,{size:28})}`,t:p.n,s:p.t,h:52,last:k===7});}),{h:340}),note('Rendering 14 of 20,000 · scrolled to 62%')],{gap:8})],
['Variable Heights',list([['Nora Becker','Announced the new parental leave policy. Everyone gets up to 14 weeks of paid leave in the first year, starting 1 January.'],['Jonas Weber','Approved.'],['Mei Tanaka','Q3 expenses are in. We came in 4% under budget, mostly thanks to fewer flights and the new travel policy.'],['Lucas Moreau','Thanks!']].map(([n,t],i,a)=>`<div style="display: flex; gap: 12px; padding: 14px 16px;${i<a.length-1?' box-shadow: inset 0 -1px 0 var(--r-line);':''}">${avatar(n,{size:32})}<div style="flex: 1; min-width: 0;"><div style="font: 600 14px/1.3 var(--r-font);">${n}</div><div style="font: 400 ${M?15:14}px/1.5 var(--r-font); color: var(--r-fg-2);">${t}</div></div></div>`))],
['Keyboard',C([list(P.slice(0,5).map((p,i,a)=>listRow({lead:avatar(p.n,{size:28}),t:p.n,s:p.t,h:48,bg:i===2?'var(--r-accent-soft)':'',last:i===a.length-1}))),`<div style="display: flex; gap: 12px; flex-wrap: wrap; font: 400 13px/1 var(--r-font); color: var(--r-fg-2);"><span>${kbd(['↑','↓'])} move</span><span>${kbd(['Home','End'])} jump</span><span>${kbd('PgDn')} page</span><span>${kbd('↵')} open</span></div>`],{gap:10})],
['Empty',box(empty({icon:'list',title:'No activity yet',body:'Changes to people and teams will be listed here.',pad:12}))]]});
return S;}
