function SPEC_FORMS(L){const {M,R,C,G,T,H,I,btn,badge,box,note,lbl,J,esc,avatar,field,check,radio,sw,seg,toggle,slider,listbox,selectBox,chip,cal,dropzone,fileRow,rte,rteBar,stage,dialog,pop,prog,kbd,list,listRow,spin,PEOPLE,tip,kv,alert}=L;
const P=PEOPLE;const FS=M?17:15;
const stepBtns=`<span style="display: flex; gap: 2px; margin-right: -6px;">${btn('',{v:'ghost',size:'xs',icon:'minus'})}${btn('',{v:'ghost',size:'xs',icon:'plus'})}</span>`;
const numF=o=>field({...o,suf:o.noStep?o.suf:(o.suf?`<span style="display: flex; align-items: center; gap: 6px;"><span style="font: 400 ${FS}px/1 var(--r-font); color: var(--r-fg-2);">${esc(o.suf)}</span>${stepBtns}</span>`:stepBtns)});
const pin=(vals,n,o={})=>{const w=M?48:44,h=M?58:52;const cells=[];for(let i=0;i<n;i++){const v=vals[i];const f=o.focus===i;if(o.group&&i&&i%o.group===0)cells.push(`<span style="width: 10px; height: 2px; border-radius: 2px; background: var(--r-fg-3); align-self: center;"></span>`);cells.push(`<span style="width: ${w}px; height: ${h}px; box-sizing: border-box; border-radius: 14px; background: ${f?'var(--r-surface)':'var(--r-fill)'}; box-shadow: ${o.error?'inset 0 0 0 2px var(--r-danger)':f?'inset 0 0 0 2px var(--r-accent)':o.done?'inset 0 0 0 2px var(--r-success)':'none'}; display: grid; place-items: center; font: 700 ${M?24:22}px/1 var(--r-font-display); font-variant-numeric: tabular-nums;${o.disabled?' opacity: 0.5;':''} flex: none;">${v==null?(f?`<span style="width: 2px; height: 24px; background: var(--r-accent);"></span>`:''):o.mask?'<span style="width: 12px; height: 12px; border-radius: 999px; background: var(--r-fg);"></span>':esc(v)}</span>`);}return `<div style="display: flex; gap: ${M?8:8}px; flex-wrap: nowrap;">${cells.join('')}</div>`;};
const tagsF=(tags,o={})=>{const st=o.state||'default';return C([o.label?`<span style="font: 600 ${M?15:13}px/1.2 var(--r-font);">${esc(o.label)}</span>`:'',`<div style="min-height: ${o.size==='sm'?32:M?56:44}px; box-sizing: border-box; border-radius: ${M?16:12}px; background: ${st==='focus'?'var(--r-surface)':'var(--r-fill)'}; box-shadow: ${st==='focus'?'inset 0 0 0 2px var(--r-accent)':st==='error'?'inset 0 0 0 2px var(--r-danger)':'none'}; padding: 6px 8px; display: flex; flex-wrap: wrap; gap: 6px; align-items: center;${st==='disabled'?' opacity: 0.5;':''}">${tags.map(t=>typeof t==='string'?chip(t,{remove:st!=='disabled'}):chip(t.l,{remove:1,error:t.err,on:t.hl})).join('')}<span style="flex: 1 1 80px; min-width: 80px; font: 400 ${FS}px/1 var(--r-font); color: ${o.typing?'var(--r-fg)':'var(--r-fg-3)'}; display: flex; align-items: center; padding: 0 4px;">${esc(o.typing||o.ph||'Add a skill')}${st==='focus'?`<span style="width: 1.5px; height: 18px; background: var(--r-accent); margin-left: 1px;"></span>`:''}</span></div>`,o.hint?`<span style="font: 400 ${M?15:13}px/1.4 var(--r-font); color: ${o.err?'var(--r-danger-text)':'var(--r-fg-2)'};">${esc(o.hint)}</span>`:''],{gap:6});};
const starP='M12 2.5l2.9 6.1 6.6.8-4.9 4.6 1.3 6.6L12 17.3l-5.9 3.3 1.3-6.6-4.9-4.6 6.6-.8z';
const heartP='M12 20.5s-8-4.9-8-11A4.5 4.5 0 0 1 12 6.6a4.5 4.5 0 0 1 8 2.9c0 6.1-8 11-8 11z';
const star=(fill,s,path=starP,col='var(--r-warning)')=>`<span style="position: relative; width: ${s}px; height: ${s}px; display: inline-block; flex: none;"><svg width="${s}" height="${s}" viewBox="0 0 24 24" style="position: absolute; inset: 0;"><path d="${path}" style="fill: var(--r-fill-strong);"></path></svg><span style="position: absolute; top: 0; left: 0; bottom: 0; width: ${fill*100}%; overflow: hidden;"><svg width="${s}" height="${s}" viewBox="0 0 24 24"><path d="${path}" style="fill: ${col};"></path></svg></span></span>`;
const rating=(v,o={})=>{const s=o.size||(M?36:28);return `<div style="display: flex; align-items: center; gap: ${o.gap??4}px;">${[1,2,3,4,5].map(i=>`<span style="display: inline-flex; border-radius: 8px;${o.focus===i?' outline: 3px solid var(--r-focus); outline-offset: 2px;':''}${o.hover&&i<=o.hover?' transform: scale(1.08);':''}">${star(Math.max(0,Math.min(1,v-i+1)),s,o.path,o.col)}</span>`).join('')}${o.label?`<span style="margin-left: 8px; font: 600 ${M?15:14}px/1 var(--r-font);">${esc(o.label)}</span>`:''}</div>`;};
const tile=(o={})=>{const s=o.s||(M?100:96);return `<div style="position: relative; width: ${s}px; height: ${s}px; border-radius: ${o.round?'999px':(M?18:16)+'px'}; background: ${o.empty?'transparent':`color-mix(in oklch, ${o.c||'var(--r-chart-2)'} 55%, var(--r-surface))`}; ${o.empty?`border: 2px dashed ${o.err?'var(--r-danger)':'var(--r-line-strong)'}; box-sizing: border-box;`:''} display: grid; place-items: center; color: ${o.empty?'var(--r-fg-2)':'#fff'}; flex: none; overflow: hidden;${o.err&&!o.empty?' box-shadow: 0 0 0 2px var(--r-danger);':''}${o.ar?` width: ${s*o.ar}px;`:''}">${o.empty?C([I(o.icon||'image-plus',22),o.label?`<span style="font: 600 11px/1.2 var(--r-font); text-align: center;">${esc(o.label)}</span>`:''],{gap:4,align:'center'}):o.init?`<span style="font: 700 ${Math.round(s*0.34)}px/1 var(--r-font-display);">${o.init}</span>`:I('image',Math.round(s*0.3))}${o.up!=null?`<span style="position: absolute; inset: 0; background: oklch(0% 0 0 / 0.45); display: grid; place-items: center;">${L.prog({circ:1,v:o.up,size:40,bare:0,tone:'accent'}).replace('font: 700 10px','font: 700 10px').replace(/color: [^;]*;/,'')}</span>`:''}${o.x?`<span style="position: absolute; top: 6px; right: 6px; width: 24px; height: 24px; border-radius: 999px; background: oklch(0% 0 0 / 0.55); color: #fff; display: grid; place-items: center;">${I('x',13)}</span>`:''}${o.edit?`<span style="position: absolute; right: ${o.round?4:6}px; bottom: ${o.round?4:6}px; width: 28px; height: 28px; border-radius: 999px; background: var(--r-surface-raised); color: var(--r-fg); box-shadow: var(--r-shadow-2); display: grid; place-items: center;">${I('camera',14)}</span>`:''}</div>`;};
const w=M?undefined:360;const col=(a,g=14)=>C(a,{gap:g,style:M?'':` max-width: ${w}px;`});
const S=[];
S.push({g:'Forms',id:'field',name:'Field',desc:'The wrapper for every form control: the label above, the control, then a hint or an error below it. Only one message shows at a time.',stories:[
['Playground',col([field({label:'Preferred name',value:'Priya',hint:'This is what colleagues see.'})])],
['Text',col([field({label:'Job title',value:'Senior Engineer'}),field({label:'Team',ph:'e.g. Platform'})])],
['Caution',col([field({label:'Start date',value:'1 Jan 2027',state:'caution',caution:'That\u2019s more than 90 days away. Is that right?'})]),{note:'Caution is for values that are allowed but unusual. It never blocks saving.'}],
['Sensitive',col([field({label:'Date of birth',value:'••/••/1991',sensitive:1,suf:'i:eye',hint:'Only you and HR can see this.'}),field({label:'Salary',value:'€92,000',sensitive:1,suf:'i:eye-off'})])],
['Missing',col([field({label:'Emergency contact',ph:'Name and phone',state:'error',error:'Add an emergency contact to finish onboarding.'})])],
['Invalid',col([field({label:'Work email',value:'priya@reach',state:'error',error:'Use a full address, like priya@reach.co.'})])],
['Disabled',col([field({label:'Employee ID',value:'RCH-00412',state:'disabled',hint:'Set by payroll. You can\u2019t change it.'}),field({label:'Manager',value:'Jonas Weber',state:'readonly',hint:'Read-only: change it in the org chart.'})])],
['Adornments',col([field({label:'Website',pre:'https://',value:'reach.co'}),field({label:'Search',pre:'i:search',ph:'Name or email',clear:0}),field({label:'Hourly rate',pre:'€',value:'48.00',suf:'per hour'})])],
['Horizontal',M?col([field({label:'First name',value:'Priya'}),field({label:'Last name',value:'Shah'}),note('Fields always stack on a phone.')]):C([field({label:'First name',value:'Priya',horizontal:1}),field({label:'Last name',value:'Shah',horizontal:1}),field({label:'Pronouns',ph:'Optional',horizontal:1,optional:1})],{gap:14}),{wide:!M}],
['A whole form',box(C([H('Personal details'),M?'':`<div style="display: grid; grid-template-columns: 1fr 1fr; gap: 14px;">${field({label:'First name',value:'Priya'})}${field({label:'Last name',value:'Shah'})}</div>`,M?field({label:'First name',value:'Priya'})+field({label:'Last name',value:'Shah'}):'',field({label:'Work email',value:'priya@reach',state:'error',error:'Use a full address, like priya@reach.co.'}),field({label:'Phone',pre:'+49',value:'151 2345 6789',optional:1}),field({label:'About',multi:1,ph:'A line or two for your profile'}),`<div style="display: flex; gap: 8px; justify-content: flex-end; ${M?'flex-direction: column-reverse;':''}">${btn('Cancel',{v:'secondary',full:M})}${btn('Save',{full:M})}</div>`],{gap:16})),{wide:!M}]]});
S.push({g:'Forms',id:'input',name:'Input',desc:'The bare text control. Use it inside Field unless it labels itself, as a search box does.',stories:[
['Playground',col([field({ph:'Type something'})])],
['Sizes',M?col([field({ph:'Compact · 44',size:'sm'}),field({ph:'Default · 56'})]):col([field({ph:'Small · 32',size:'sm'}),field({ph:'Medium · 40'}),field({ph:'Large · 48',size:'lg'})],10)],
['States',col([field({ph:'Default'}),field({value:'Focused',state:'focus'}),field({value:'Invalid',state:'error'}),field({value:'Caution',state:'caution'}),field({value:'Disabled',state:'disabled'}),field({value:'Read-only',state:'readonly'})],10)],
['Adornments',col([field({pre:'i:search',ph:'Search',suf:M?'':kbd(['⌘','K'])}),field({pre:'i:mail',value:'priya@reach.co',suf:'i:circle-check'}),field({value:'Loading…',suf:spin(16)})],10)],
['Textarea',col([field({multi:1,value:'Happy to cover Amara\u2019s design reviews while she\u2019s out. I\u2019ll check in with Omar on Friday.',state:'focus'}),`<span style="align-self: flex-end; font: 400 12px/1 var(--r-font); color: var(--r-fg-3);">96 / 500</span>`],6)]]});
S.push({g:'Forms',id:'number-field',name:'NumberField',desc:'For counts and amounts. Empty means no value, and it never turns into 0 by itself.',stories:[
['Playground',col([numF({label:'Days',value:'5'})])],
['Null is not zero',col([numF({label:'Overtime hours',ph:'Not set',hint:'Empty means not reported, which is different from 0.'}),numF({label:'Overtime hours',value:'0',hint:'Zero means reported as none.'})])],
['Decimals and locale',col([numF({label:'FTE (en-GB)',value:'0.8'}),numF({label:'FTE (de-DE)',value:'0,8'}),numF({label:'Salary (fr-FR)',value:'92 000,00',suf:'€',noStep:1})])],
['Prefixes, suffixes and sizes',col([numF({label:'Bonus',pre:'€',value:'2,500',size:'sm'}),numF({label:'Allowance',value:'20',suf:'%'}),numF({label:'Notice period',value:'3',suf:'months',size:'lg'})],10)],
['Bounds and validation',col([numF({label:'Days off',value:'18',state:'error',error:'You have 14.5 days left. Enter 14.5 or fewer.'}),numF({label:'Team size',value:'1',hint:'Minimum 1. The minus button is off at the minimum.'})])],
['Disabled and read-only',col([numF({label:'Carry-over',value:'5',state:'disabled'}),field({label:'Accrued',value:'23.5 days',state:'readonly'})])]]});
S.push({g:'Forms',id:'password-field',name:'PasswordField',desc:'Masked by default with a reveal button. Always allow pasting, so password managers work.',stories:[
['Playground',col([field({label:'Password',value:'••••••••••',suf:btn('',{v:'ghost',size:'xs',icon:'eye'}),tight:1})])],
['Signing in',box(C([R([L.mark(36),H('Sign in to Reach')],{gap:10}),field({label:'Email',value:'priya@reach.co'}),field({label:'Password',value:'••••••••••',state:'focus',suf:btn('',{v:'ghost',size:'xs',icon:'eye'}),tight:1}),`<a href="#" style="font: 500 14px/1 var(--r-font); align-self: flex-end;">Forgot password?</a>`,btn('Sign in',{full:1})],{gap:14}),{w:M?undefined:380})],
['Setting a new one',col([field({label:'New password',value:'Correct-Horse-7',suf:btn('',{v:'ghost',size:'xs',icon:'eye-off'}),tight:1}),prog({v:75,tone:'success',label:'Strong',right:'3 of 4'}),C([['At least 12 characters',1],['A number or symbol',1],['Not a common password',1],['Not your name or email',0]].map(([l,ok])=>`<span style="display: flex; gap: 8px; align-items: center; font: 400 ${M?15:13}px/1.3 var(--r-font); color: ${ok?'var(--r-fg)':'var(--r-fg-2)'};">${I(ok?'circle-check':'circle',16,ok?'var(--r-success)':'var(--r-fg-3)')}${l}</span>`),{gap:6})])],
['Paste works: deliberately',col([field({label:'Password',value:'••••••••••••••••',state:'focus',suf:btn('',{v:'ghost',size:'xs',icon:'eye'}),tight:1}),alert({tone:'success',title:'Pasted from your password manager',body:'We never block paste. Blocking it pushes people to weaker passwords.'})])],
['Invalid, disabled, sizes',col([field({label:'Password',value:'•••••',state:'error',error:'That password isn\u2019t right. 2 tries left.',suf:'i:eye'}),field({label:'Password',value:'••••••••',state:'disabled',suf:'i:eye'}),field({value:'••••••••',size:'sm',suf:'i:eye'})])]]});
S.push({g:'Forms',id:'pin-input',name:'PinInput',desc:'One box for each character. Typing moves to the next box, and pasting fills every box at once.',stories:[
['Playground',pin(['4','8'],6,{focus:2})],
['Pasting a code',C([pin(['4','8','2','9','1','7'],6,{done:1}),note('Pasted 482917. All six boxes filled, and the form submitted.')])],
['A verification screen',box(C([`<span style="width: 48px; height: 48px; border-radius: 999px; background: var(--r-accent-soft); color: var(--r-accent-text); display: grid; place-items: center;">${I('smartphone',22)}</span>`,H('Check your phone',{s:M?22:20}),note('We sent a 6-digit code to +49 ••• ••• 6789.'),pin(['4','8','2'],6,{focus:3,group:3}),`<span style="font: 500 ${M?15:13}px/1 var(--r-font); color: var(--r-fg-2);">Resend in 0:24</span>`],{gap:12,align:'center',style:' text-align: center;'}))],
['Lengths, groups and letters',C([pin(['1','2','3','4'],4),pin(['4','8','2','9','1','7'],6,{group:3}),pin(['K','7','X','2'],4),note('Letters are shown in capitals and matched without case.')],{gap:14})],
['A stored PIN',C([pin(['•','•','•','•'],4,{mask:1}),pin([null,null,null,null],4,{error:1}),`<span style="font: 400 ${M?15:13}px/1.4 var(--r-font); color: var(--r-danger-text);">Wrong PIN. 2 tries left before it locks for 5 minutes.</span>`,pin(['1','2','3','4'],4,{disabled:1})],{gap:12})]]});
S.push({g:'Forms',id:'tags-input',name:'TagsInput',desc:'A free list of short values, like skills or email addresses. Enter or a comma adds a tag. Backspace in an empty input removes the last one.',stories:[
['Playground',col([tagsF(['React','TypeScript','Design systems'],{label:'Skills'})])],
['From the keyboard',col([tagsF(['React','TypeScript'],{state:'focus',typing:'Figma',label:'Skills'}),`<div style="display: flex; gap: 12px; flex-wrap: wrap; font: 400 13px/1 var(--r-font); color: var(--r-fg-2);"><span>${kbd('↵')} add</span><span>${kbd(',')} add</span><span>${kbd('⌫')} remove last</span><span>${kbd('←')} select a tag</span></span></div>`])],
['Validation and duplicates',col([tagsF(['priya@reach.co',{l:'jonas@',err:1},{l:'priya@reach.co',hl:1}],{label:'Invite',state:'error',hint:'jonas@ isn\u2019t a full address, and priya@reach.co is already on the list.',err:1})])],
['Markup is escaped',col([tagsF(['<script>alert(1)</script>','<b>bold</b>'],{label:'Tags'}),note('Tags are always plain text. What you type is exactly what shows.')])],
['A limit',col([tagsF(['Berlin','London','Paris','Madrid','Remote'],{label:'Locations',hint:'5 of 5. Remove one to add another.',ph:''})])],
['Sizes and states',col([tagsF(['Small'],{size:'sm'}),tagsF(['Default']),tagsF(['Disabled'],{state:'disabled'})],10)]]});
S.push({g:'Forms',id:'rating',name:'Rating',desc:'Pick a whole number from 1 to 5. Always say what each number means, because a star alone is ambiguous.',stories:[
['Playground',rating(3)],
['With meanings',C([rating(4,{label:'Exceeds expectations'}),note('1 Below · 2 Partly meets · 3 Meets · 4 Exceeds · 5 Outstanding')])],
['From the keyboard',C([rating(3,{focus:3}),`<div style="display: flex; gap: 12px; font: 400 13px/1 var(--r-font); color: var(--r-fg-2);"><span>${kbd(['←','→'])} change</span><span>${kbd('0')} clear</span></div>`])],
['Displaying an average',R([rating(4.3,{size:M?22:18,gap:2}),T('4.3',{w:700,s:M?17:15}),T('from 18 reviews',{c:'var(--r-fg-2)',s:M?15:13})],{gap:8})],
['Sizes and symbols',C([rating(4,{size:16}),rating(4,{size:24}),rating(4,{size:36}),rating(3,{size:28,path:heartP,col:'var(--r-danger)'})],{gap:12})],
['In a review form',box(C([H('Mid-year review'),C([lbl('Delivery'),rating(4,{label:'Exceeds'})],{gap:8}),C([lbl('Collaboration'),rating(5,{label:'Outstanding'})],{gap:8}),field({label:'Comments',multi:1,value:'Priya led the payroll migration and unblocked two teams.'}),btn('Submit review',{full:M})],{gap:16}))]]});
const teams=[{l:'Engineering'},{l:'Design',sel:1},{l:'Sales'},{l:'Support'},{l:'Finance'}];
S.push({g:'Forms',id:'select',name:'Select',desc:'Pick one value from a short, fixed list. Over about 10 options, use Combobox instead.',stories:[
['Playground',C([selectBox({value:'Design',state:'focus',w}),listbox(teams)],{gap:6})],
['Placeholder',col([selectBox({ph:'Choose a team'})])],
['Grouped',listbox([{h:'Europe'},{l:'Berlin',sel:1},{l:'London'},{l:'Paris'},{h:'Asia'},{l:'Tokyo'},{l:'Singapore'}])],
['In a field',col([selectBox({label:'Contract type',value:'Permanent',hint:'Fixed-term contracts need an end date.'})])],
['Controlled',col([selectBox({label:'Pay frequency',value:'Monthly'}),note('The value comes from the parent. Changing it resets the pay-day field below.'),selectBox({label:'Pay day',value:'Last working day'})])],
['Disabled',col([selectBox({label:'Currency',value:'EUR',state:'disabled',hint:'Set by your entity.'}),listbox([{l:'Full-time',sel:1},{l:'Part-time'},{l:'Contractor',disabled:1,d:'Not available in Germany'}])])]]});
const ppl=P.slice(0,5).map(p=>({l:p.n,av:p.n,d:p.r}));
S.push({g:'Forms',id:'combobox',name:'Combobox',desc:'Type to filter a long list. Matches are highlighted, and Enter picks the first one.',stories:[
['Playground',C([field({value:'eng',pre:'i:search',state:'focus',w}),listbox([{l:'Engineering',hl:'eng',active:1},{l:'Engineering Management',hl:'eng'},{l:'Sales Engineering',hl:'eng'}])],{gap:6})],
['Grouped options',listbox([{h:'Teams'},{l:'Engineering'},{l:'Design'},{h:'People'},{l:'Priya Shah',av:'Priya Shah'},{l:'Jonas Weber',av:'Jonas Weber'}],{search:'e'})],
['Multiple',listbox([{l:'Berlin',sel:1},{l:'London',sel:1},{l:'Paris'},{l:'Madrid'},{l:'Remote',sel:1}],{multi:1,foot:'3 selected'})],
['Multiple, with removable chips',col([tagsF(['Priya Shah','Jonas Weber','Mei Tanaka'].map(n=>n),{label:'Reviewers',ph:'Add a reviewer',state:'focus'})])],
['With icons and avatars',R([listbox(ppl.slice(0,4)),listbox([{l:'Vacation',icon:'sun'},{l:'Sick leave',icon:'thermometer'},{l:'Parental',icon:'baby'},{l:'Unpaid',icon:'briefcase'}])],{align:'flex-start',gap:12})],
['Server-side search',C([field({value:'mor',pre:'i:search',suf:spin(16),state:'focus',w}),listbox([{l:'Lucas Moreau',av:'Lucas Moreau',hl:'mor',d:'Sales'}],{foot:'Searching all 312 people…'})],{gap:6})],
['Sizes',col(M?[field({value:'Design',size:'sm',suf:'i:chevrons-up-down'}),field({value:'Design',suf:'i:chevrons-up-down'})]:[field({value:'Design',size:'sm',suf:'i:chevrons-up-down'}),field({value:'Design',suf:'i:chevrons-up-down'}),field({value:'Design',size:'lg',suf:'i:chevrons-up-down'})],10)],
['In a Field',col([field({label:'Manager',pre:avatar('Jonas Weber',{size:24}),value:'Jonas Weber',suf:'i:chevrons-up-down',hint:'Approves time off and expenses.'})])],
['In A Dialog',stage(dialog({title:'Change manager',close:1,content:C([field({label:'New manager',value:'No',state:'focus',pre:'i:search'}),listbox([{l:'Nora Becker',av:'Nora Becker',hl:'No',active:1},{l:'Omar Haddad',av:'Omar Haddad'}],{w:M?undefined:380})],{gap:6}),actions:[btn('Cancel',{v:'secondary'}),btn('Change')]}),{h:M?520:420}),{wide:!M}]]});
S.push({g:'Forms',id:'checkbox',name:'Checkbox',desc:'For turning options on or off as part of a form you then save. For a setting that applies straight away, use Switch.',stories:[
['Playground',check('on','Send me a weekly summary')],
['Checkbox states',G([['off','Off'],['on','On'],['mixed','Mixed']].map(([s,l])=>C([check(s),note(l)],{gap:8,align:'flex-start'})).concat([C([check('off','',{focus:1}),note('Focus')],{gap:8}),C([check('on','',{disabled:1}),note('Disabled')],{gap:8}),C([check('off','',{error:1}),note('Required')],{gap:8})]),90)],
['Indeterminate',C([check('mixed','All of Engineering'),`<div style="padding-left: 28px; display: flex; flex-direction: column; gap: 10px;">${check('on','Platform')}${check('on','Payroll')}${check('off','Mobile')}</div>`],{gap:10})],
['Checkbox or switch?',`<div style="display: grid; grid-template-columns: ${M?'1fr':'1fr 1fr'}; gap: 12px;">${box(C([lbl('Checkbox · saved with the form'),check('on','Include in payroll run'),btn('Save',{size:'sm',style:' align-self: flex-start;'})]))}${box(C([lbl('Switch · applies straight away'),sw(true,'Email notifications')]))}</div>`]]});
S.push({g:'Forms',id:'radio-group',name:'RadioGroup',desc:'Pick exactly one of two to five options when everyone needs to see the choices side by side.',stories:[
['Playground',C([radio(true,'Monthly'),radio(false,'Every two weeks'),radio(false,'Weekly')],{gap:12})],
['With consequences spelled out',C([radio(false,'Keep their data',{bold:1,desc:'Their profile stays read-only in the directory for 7 years.'}),radio(true,'Anonymise their data',{bold:1,desc:'Their name is replaced with an ID. This can\u2019t be undone.'})],{gap:16})],
['As cards',C([['Standard','€0 · 5 days',true],['Express','€15 · next day',false]].map(([t,d,on])=>`<div style="padding: 16px; border-radius: ${M?18:14}px; background: ${on?'var(--r-accent-soft)':'var(--r-surface)'}; box-shadow: ${on?'inset 0 0 0 2px var(--r-accent)':'var(--r-shadow-1)'}; display: flex; gap: 12px; align-items: center;">${radio(on)}<span style="flex: 1;">${T(t,{w:600})}<br>${note(d)}</span>${I(t==='Standard'?'truck':'zap',20,'var(--r-fg-2)')}</div>`),{gap:10})],
['Horizontal',M?C([seg(['Mr','Ms','Mx','None'],3,{full:1}),note('On a phone, a horizontal group becomes a segmented control.')]):R([radio(true,'Full-time'),radio(false,'Part-time'),radio(false,'Contractor')],{gap:24})],
['A disabled option',C([radio(true,'Bank transfer'),radio(false,'Cheque',{disabled:1,desc:'Not offered in Germany'}),radio(false,'Cash')],{gap:12})]]});
S.push({g:'Forms',id:'switch',name:'Switch',desc:'For a setting that applies the moment you flip it. If it takes a moment, show a spinner and roll back if it fails.',stories:[
['Playground',R([sw(true),sw(false)],{gap:16})],
['With a label',col([sw(true,'Email notifications',{desc:'A summary every Monday at 9:00'})])],
['A settings list',L.list([['Requests to approve',true],['Team birthdays',false],['Payday reminders',true],['Product news',false]].map(([l,on],i,a)=>`<div style="padding: 0 ${M?16:18}px; min-height: ${M?60:52}px; display: flex; align-items: center;${i<a.length-1?' box-shadow: inset 0 -1px 0 var(--r-line);':''}">${sw(on,l)}</div>`))],
['Disabled',col([sw(true,'Two-factor sign-in',{disabled:1,desc:'Required by your organisation'}),sw(false,'Public profile',{disabled:1})])],
['Committing, and failing',col([sw(true,'Share calendar',{loading:1,desc:'Saving…'}),sw(false,'Share calendar',{err:'Couldn\u2019t save. We turned it back off.'})])]]});
S.push({g:'Forms',id:'toggle',name:'Toggle',desc:'A button that stays pressed. Use it for view options and formatting, not for settings.',stories:[
['Playground',R([toggle('Bold',true,{icon:'bold'}),toggle('Bold',false,{icon:'bold'})],{gap:8})],
['Variants',R([toggle('Fill',true),toggle('Fill',false),toggle('Outline',true,{v:'outline'}),toggle('Outline',false,{v:'outline'}),toggle('Ghost',true,{v:'ghost'}),toggle('Ghost',false,{v:'ghost'})],{gap:8})],
['Icon only',R([toggle('',true,{icon:'bold',square:1}),toggle('',false,{icon:'italic',square:1}),toggle('',false,{icon:'underline',square:1}),toggle('',true,{icon:'star'})],{gap:6})],
['Segmented, one of several',C([seg(['Day','Week','Month'],1,{full:M}),seg([['','list'],['','layout-grid'],['','network']],0)],{gap:12,align:'flex-start'})],
['Segmented: several at once',C([seg([['','bold'],['','italic'],['','underline'],['','strikethrough']],[0,2]),note('Several can be on at once. Each one is its own toggle.')],{align:'flex-start'})],
['Sizes',R(M?[toggle('Small',true,{size:'sm'}),toggle('Default',true)]:[toggle('Small',true,{size:'sm'}),toggle('Medium',true),toggle('Large',true,{size:'lg'})],{gap:8})]]});
S.push({g:'Forms',id:'slider',name:'Slider',desc:'For picking a rough value where the range matters more than the exact number. Pair it with a number input when the exact value matters.',stories:[
['Playground',slider({v:60,tip:1,fmt:v=>v+'%'})],
['Two-thumb range',C([slider({v:[40,75],tip:1,fmt:v=>'€'+v+'k',min:20,max:120}),note('Salary band: €40k to €75k')])],
['Discrete steps',slider({v:3,min:0,max:5,steps:5,labels:['0','1','2','3','4','5']})],
['Paired with a number input',R([`<div style="flex: 1 1 160px;">${slider({v:80})}</div>`,`<div style="width: 110px;">${numF({value:'80',suf:'%',noStep:1})}</div>`],{gap:16})],
['Vertical',R([slider({v:70,vertical:1}),slider({v:[20,60],vertical:1}),slider({v:40,vertical:1,tip:1})],{gap:40,justify:'center',style:' padding: 8px 0;'})],
['Disabled',slider({v:45,disabled:1})]]});
S.push({g:'Forms',id:'calendar',name:'Calendar',desc:'A month grid for picking days. It shows leave, holidays and blocked days so you don\u2019t have to guess.',stories:[
['Playground',cal({sel:[14],today:1})],
['Range',cal({range:[14,18],today:1})],
['Weekends and holidays blocked',cal({noWeekends:1,blocked:[3],legend:[['neutral','3 Oct · Day of German Unity']]})],
['Existing leave marked',cal({marks:{6:'info',7:'info',8:'info',21:'success',22:'success',27:'warning'},legend:[['info','Your leave'],['success','Team leave'],['warning','Pending']]})],
['Locales and week starts',R([cal({ws:1,loc:'de-DE',heads:['Mo','Di','Mi','Do','Fr','Sa','So'],w:M?undefined:260}),cal({ws:0,loc:'en-US',heads:['Su','Mo','Tu','We','Th','Fr','Sa'],w:M?undefined:260})],{gap:24,align:'flex-start'}),{wide:!M}]]});
const dp=o=>field({...o,suf:'i:calendar'});
S.push({g:'Forms',id:'date-picker',name:'DatePicker',desc:'A field that opens a calendar. You can always type the date instead.',stories:[
['Playground',C([dp({label:'Start date',value:'14 Oct 2026',state:'focus',w}),pop(cal({sel:[14]}),{w:M?undefined:312})],{gap:6})],
['Range with presets',pop(R([C(['Today','Next week','Next 2 weeks','This month','Custom'].map((x,i)=>`<span style="height: 34px; padding: 0 12px; border-radius: 10px; display: flex; align-items: center; font: ${i===1?600:500} 14px/1 var(--r-font); background: ${i===1?'var(--r-accent-soft)':'transparent'}; color: ${i===1?'var(--r-accent-text)':'var(--r-fg)'};">${x}</span>`),{gap:2,style:M?' flex-direction: row; flex-wrap: wrap;':' width: 130px;'}),cal({range:[12,16],w:M?undefined:260})],{gap:16,align:'flex-start'}),{w:M?undefined:460}),{wide:!M}],
['With a valid window',C([dp({label:'Last day',value:'30 Oct 2026',hint:'Between 1 and 31 October'}),pop(cal({sel:[30],win:[1,31],blocked:[1,2,3,4,5]}),{w:M?undefined:312})],{gap:6})],
['A start and an end',M?col([dp({label:'From',value:'Mon 14 Oct'}),dp({label:'To',value:'Fri 18 Oct',state:'focus'}),note('5 working days')]):R([dp({label:'From',value:'14 Oct 2026',flex:'1'}),I('arrow-right',18,'var(--r-fg-3)'),dp({label:'To',value:'18 Oct 2026',state:'focus',flex:'1'})],{gap:10,align:'flex-end'})],
['Sizes',col(M?[dp({value:'14 Oct',size:'sm'}),dp({value:'14 Oct 2026'})]:[dp({value:'14 Oct',size:'sm'}),dp({value:'14 Oct 2026'}),dp({value:'14 October 2026',size:'lg'})],10)]]});
S.push({g:'Forms',id:'typed-fields',name:'Typed fields',desc:'Fields for a specific kind of value. Each one brings the right keyboard, format and checks.',stories:[
['Every type',`<div style="display: grid; grid-template-columns: repeat(auto-fill, minmax(min(100%, 220px), 1fr)); gap: 14px;">${[['Email','priya@reach.co','i:mail'],['URL','reach.co','i:link'],['Phone','+49 151 2345 6789','i:phone'],['Money','€ 4,280.00','i:euro'],['Percent','20 %','i:percent'],['Date','14 Oct 2026','i:calendar'],['Time','09:30','i:clock'],['Duration','7h 30m','i:timer'],['IBAN','DE89 3704 0044 0532 01','i:landmark'],['Postcode','10115','i:map-pin']].map(([l,v,ic])=>field({label:l,value:v,pre:ic})).join('')}</div>`,{wide:!M}],
['Search',col([field({pre:'i:search',value:'Priya',clear:1,state:'focus',suf:M?'':kbd('Esc')}),field({pre:'i:search',ph:'Search people, teams and documents',suf:M?'':kbd(['⌘','K'])})])],
['Money',col([field({label:'Amount',pre:'€',value:'1,240.50',suf:`<span style="font: 600 13px/1 var(--r-font); color: var(--r-fg-2); display: flex; align-items: center; gap: 2px;">EUR${I('chevron-down',13)}</span>`}),field({label:'Refund',pre:'−€',value:'86.00',hint:'Negative amounts use a true minus sign.'})])],
['Phone number',col([field({label:'Mobile',pre:`<span style="display: flex; align-items: center; gap: 6px; font: 500 ${FS}px/1 var(--r-font); padding-right: 10px; box-shadow: inset -1px 0 0 var(--r-line-strong);">🇩🇪 +49${I('chevron-down',13)}</span>`,value:'151 2345 6789'}),field({label:'Mobile',value:'151 234',state:'error',error:'German mobile numbers have 10 or 11 digits.'})])],
['On a phone',M?C([field({label:'Amount',pre:'€',value:'248.00',state:'focus'}),`<div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 6px; padding: 8px; border-radius: 22px; background: var(--r-fill);">${['1','2','3','4','5','6','7','8','9','.','0','⌫'].map(k=>`<span style="height: 48px; border-radius: 12px; background: var(--r-surface); display: grid; place-items: center; font: 500 22px/1 var(--r-font);">${k}</span>`).join('')}</div>`,note('Money opens the decimal keypad. Email, phone and URL each open their own keyboard.')]):L.phoneMini(C([T('Expense',{s:20,w:700,d:1}),field({label:'Amount',pre:'€',value:'248.00',state:'focus'}),`<div style="display: grid; grid-template-columns: repeat(3, 1fr); gap: 5px; padding: 6px; border-radius: 16px; background: var(--r-fill); margin-top: 60px;">${['1','2','3','4','5','6','7','8','9','.','0','⌫'].map(k=>`<span style="height: 38px; border-radius: 10px; background: var(--r-surface); display: grid; place-items: center; font: 500 18px/1 var(--r-font);">${k}</span>`).join('')}</div>`],{gap:12}),{h:500})]]});
S.push({g:'Forms',id:'image-uploader',name:'ImageUploader',desc:'Upload images with a preview. It checks size and file type before uploading, and says exactly what went wrong.',stories:[
['Playground',R([tile({empty:1,label:'Add photo'})],{gap:10})],
['Several files',R([tile({c:'var(--r-chart-2)',x:1}),tile({c:'var(--r-chart-3)',x:1}),tile({c:'var(--r-chart-4)',x:1}),tile({empty:1,label:'Add'})],{gap:10})],
['With a dimension floor',C([R([tile({c:'var(--r-chart-5)',err:1}),tile({empty:1})],{gap:10}),`<span style="font: 400 ${M?15:13}px/1.4 var(--r-font); color: var(--r-danger-text);">office.jpg is 640 × 480. Use at least 1200 × 800.</span>`])],
['In flight',R([tile({c:'var(--r-chart-2)',up:64}),tile({c:'var(--r-chart-6)',up:22}),tile({c:'var(--r-chart-3)',x:1})],{gap:10})],
['Invalid and disabled',C([R([tile({empty:1,err:1,icon:'file-x',label:'Not an image'}),`<div style="opacity: 0.45;">${tile({empty:1,label:'Disabled'})}</div>`],{gap:10}),`<span style="font: 400 ${M?15:13}px/1.4 var(--r-font); color: var(--r-danger-text);">notes.pdf is a PDF. Use PNG, JPG or WebP.</span>`])],
['AvatarUploader',R([tile({round:1,init:'PS',c:'var(--r-accent)',edit:1,s:96}),C([btn('Change photo',{v:'secondary',size:'sm'}),btn('Remove',{v:'ghost',size:'sm',style:' color: var(--r-danger-text);'})],{gap:6,align:'flex-start'})],{gap:20})],
['AvatarUploader — shapes and ratios',R([tile({round:1,c:'var(--r-chart-2)',s:80}),tile({c:'var(--r-chart-2)',s:80}),tile({c:'var(--r-chart-2)',s:80,ar:1.6}),`<div style="width: ${M?'100%':'auto'};">${note('Circle for people, rounded square for teams and apps, 16:10 for covers.')}</div>`],{gap:12})],
['AvatarUploader — an already-stored image',R([tile({round:1,c:'var(--r-chart-4)',s:88,edit:1}),C([T('photo.jpg',{w:600}),note('Uploaded 3 Mar 2025 · 240 KB')],{gap:2})],{gap:16})],
['AvatarUploader — the photo is the control',C([`<div style="position: relative; display: inline-flex;">${tile({round:1,c:'var(--r-chart-4)',s:112})}<span style="position: absolute; inset: 0; border-radius: 999px; background: oklch(0% 0 0 / 0.45); color: #fff; display: grid; place-items: center;">${C([I('camera',22),`<span style="font: 600 12px/1 var(--r-font);">Change</span>`],{gap:4,align:'center'})}</span></div>`,note('On hover or focus the photo shows "Change". On touch, tapping it opens the options.')],{align:'center'})]]});
S.push({g:'Forms',id:'dropzone',name:'Dropzone',desc:'A large target for dragging files onto. Clicking it always opens the file browser too.',stories:[
['Playground',C([dropzone({}),dropzone({over:1})],{gap:10})],
['Inline, in a row',dropzone({inline:1,title:'Attach receipts',hint:'PDF or image, up to 10 MB each'})],
['Disabled',dropzone({disabled:1,hint:'Uploads are closed for this payroll run'})]]});
S.push({g:'Forms',id:'rich-text-editor',name:'RichTextEditor',desc:'Formatted text for policies, notes and comments. It stores safe HTML and reads it back the same way.',stories:[
['Playground',rte({state:'focus',on:['bold'],body:'Welcome to the team, <b>Lucas</b>! Your first week:<ul style="margin: 6px 0; padding-left: 20px;"><li>Laptop pickup on Monday</li><li>Lunch with Tom on Wednesday</li></ul>'}),{wide:!M}],
['A comment box',rte({bar:false,h:64,ph:'Add a comment…',foot:`<span style="display: flex; gap: 2px; color: var(--r-fg-2);">${I('at-sign',16)}${I('paperclip',16)}${I('smile',16)}</span>${btn('Comment',{size:'sm',disabled:1})}`})],
['Every group',rte({groups:[['undo-2','redo-2'],['heading-1','heading-2','heading-3','pilcrow'],['bold','italic','underline','strikethrough','highlighter'],['list','list-ordered','list-checks','quote'],['align-left','align-center','align-right'],['link','image','table','code','minus']],h:60}),{wide:!M}],
['No toolbar',C([rte({bar:false,h:80,body:'Select text to format it. Shortcuts still work: <b>⌘B</b>, <i>⌘I</i>.'}),note('A small toolbar pops up over selected text.')])],
['Invalid, disabled and read-only',C([rte({state:'error',h:48,bar:false,ph:'Reason for leaving'}),`<span style="font: 400 ${M?15:13}px/1.4 var(--r-font); color: var(--r-danger-text); margin-top: -4px;">Add a reason before you submit.</span>`,rte({state:'disabled',h:48}),rte({state:'readonly',bar:false,h:48,body:'Approved by <b>Nora Becker</b> on 3 Oct.'})],{gap:10})],
['What it stores, and how it reads back',`<div style="display: grid; grid-template-columns: ${M?'1fr':'1fr 1fr'}; gap: 12px;">${rte({bar:false,h:80,body:'Hello <b>team</b>, see <a href="#">the policy</a>.'})}<pre style="margin: 0; padding: 14px; border-radius: 14px; background: var(--r-fill); font: 400 12px/1.6 var(--r-mono); color: var(--r-fg-2); white-space: pre-wrap;">${esc('<p>Hello <strong>team</strong>, see <a href="https://reach.co/policy" rel="noopener">the policy</a>.</p>')}</pre></div>`,{wide:!M}]]});
S.push({g:'Forms',id:'file-uploader',name:'FileUploader',desc:'Upload documents with a row for each file. Each row shows progress, lets you retry, and says why a file was refused.',stories:[
['Playground',C([dropzone({}),fileRow({n:'contract-priya-shah.pdf',meta:'PDF · 2.1 MB'})],{gap:10})],
['Uploading, failing, retrying',C([fileRow({n:'passport.jpg',state:'up',v:62,meta:'1.2 of 1.9 MB · 4 s left',thumb:'color-mix(in oklch, var(--r-chart-2) 55%, var(--r-surface))'}),fileRow({n:'payslip-august.pdf',state:'error',meta:'Upload failed: the connection dropped.'}),fileRow({n:'offer-letter.pdf',meta:'PDF · 480 KB'})],{gap:8})],
['Everything refused says why',C([fileRow({n:'holiday.mov',state:'error',icon:'file-video',meta:'Videos aren\u2019t accepted. Use PDF, PNG or JPG.'}),fileRow({n:'scan-all-pages.pdf',state:'error',meta:'38 MB is over the 10 MB limit.'}),fileRow({n:'contract.pdf',state:'error',meta:'Already uploaded on 2 Sep.'})],{gap:8})],
['One file, as a button',C([R([btn('Upload CV',{v:'secondary',icon:'upload'}),note('PDF, up to 5 MB')],{gap:12}),fileRow({n:'cv-lucas-moreau.pdf',meta:'PDF · 820 KB'})],{gap:10})],
['Hostile filenames',C([fileRow({n:'<img src=x onerror=alert(1)>.pdf',meta:'Shown as plain text'}),fileRow({n:'invoice.pdf.exe',state:'error',icon:'shield-alert',meta:'Blocked: this is a program, not a PDF.'}),fileRow({n:'a-very-long-file-name-that-keeps-going-and-going-until-it-truncates.pdf',meta:'Truncated in the middle on hover'})],{gap:8})],
['Disabled, invalid and full',C([dropzone({disabled:1,inline:1,hint:'Uploads are off while payroll runs'}),dropzone({error:'Add at least one receipt.',inline:1}),dropzone({inline:1,disabled:1,title:'5 of 5 files',hint:'Remove a file to add another.'})],{gap:10})]]});
return S;}
