function SPEC_CHARTS(L){const {M,R,C,G,T,H,I,btn,badge,box,note,lbl,J,esc,avatar,field,seg,menu,pop,chip,kv,list,listRow,kbd,table,stat,spark,money,ccard,bars,line,donut,heat,funnel,gantt,org,orgTD,orgLR,orgCanvas,ocard,waterfall,bands,scatter,legend,tip,alert,empty,CH,PEOPLE}=L;
const MO=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const hires=MO.map((m,i)=>[M?m[0]:m,[6,9,7,12,10,8,5,11,14,0,0,0][i]]);
const HEAD=[263,266,271,274,279,285,289,294,297,301,306,312],PLAN=[263,268,273,278,283,288,293,298,303,308,313,318],LEAV=[4,3,5,2,4,6,3,2,4,3,2,4];
const qx=['Q1','Q2','Q3','Q4'];
const cc=(o)=>ccard(o);
const T0=()=>({n:'Nora Becker',r:'Chief Executive',k:[{n:'Jonas Weber',r:'CTO',k:[{n:'Priya Shah',r:'Senior Engineer'},{n:'Omar Haddad',r:'Backend Engineer'},{n:'Yuki Sato',r:'iOS Engineer'}]},{n:'Zara Ahmed',r:'CFO',k:[{n:'Mei Tanaka',r:'Data Analyst'}]},{n:'Tom Fischer',r:'VP Sales',k:[{n:'Lucas Moreau',r:'Account Executive'},{vacant:1,n:'',r:'Sales Engineer'}]}]});
const walk=(n,f,d=0,p=null)=>{f(n,d,p);(n.k||[]).forEach(c=>walk(c,f,d+1,n));return n;};
const tr=(f)=>walk(T0(),f||(()=>{}));
const sc=M?1:0.78;
const oc=(t,o={})=>org(t,{scale:o.scale??sc,h:o.h,dir:o.dir,mini:o.mini,controls:o.controls,top:o.top,card:o.card,tree:o.tree,left:o.left});
const days=['Mon','Tue','Wed','Thu','Fri','Sat','Sun','Mon','Tue','Wed','Thu','Fri'];
const cover=[{l:'Amara Okafor',av:1,items:[{s:0,e:5,l:'Vacation',t:'info'}]},{l:'Omar Haddad',av:1,items:[{s:2,e:4,l:'Sick',t:'danger'}]},{l:'Priya Shah',av:1,items:[{s:7,e:12,l:'Vacation',t:'info'}]},{l:'Yuki Sato',av:1,items:[{s:4,e:5,l:'Training',t:'accent'}]}];
const smallMult=['Engineering','Sales','Design','Support'].map((t,i)=>{const s=[[80,86,92,98,104,112,118,124],[48,50,55,58,60,61,63,64],[20,22,22,24,25,26,27,28],[40,42,45,44,46,47,47,48]][i];return box(C([R([T(t,{w:600,s:13}),`<span style="margin-left: auto; font: 700 16px/1 var(--r-font-display);">${s[s.length-1]}</span>`]),line([s],{h:60,nogrid:1,colors:[CH[i]],area:1,sw:2})],{gap:8}),{p:14});});
const S=[];
S.push({g:'Charts',id:'charts-overview',name:'Overview',desc:'Every chart puts the number first and the chart under it. One colour means one series, and categories use the chart palette in order.',stories:[
['Every chart',`<div style="display: grid; grid-template-columns: repeat(auto-fill, minmax(min(100%, 260px), 1fr)); gap: 12px;">${[cc({t:'Bar',body:bars(hires.slice(0,9),{h:90,hi:8})}),cc({t:'Trend',body:line([HEAD],{h:90,area:1})}),cc({t:'Distribution',body:donut([['Eng',124],['Sales',64],['Support',48],['Other',76]],{size:90,legend:false})}),cc({t:'Heatmap',body:heat([[1,3,5,2,4],[2,6,8,4,1],[0,2,4,7,3]],{scale:false})}),cc({t:'Funnel',body:funnel([['Applied',420],['Screen',180],['Offer',24]])}),cc({t:'Movement',body:waterfall([['Start',297,'total'],['In',18],['Out',-3],['End',312,'total']],{h:90})})].join('')}</div>`,{wide:1}],
['The accessibility contract',C([cc({t:'Hires, 2026',v:'82',body:bars(hires,{hi:8,h:M?120:150})}),kv([['Title and summary','Read first: "82 hires in 2026. The most was 14 in September."'],['Data table','A visually hidden table carries every value.'],['Keyboard','Tab into the chart, and the arrow keys move between points.'],['Colour','Never the only signal. Labels and patterns carry it too.']],{kw:170})],{gap:14}),{wide:1}],
['At every width',R([`<div style="flex: 3 1 360px; min-width: 0;">${cc({t:'Wide',body:bars(hires,{h:120,hi:8})})}</div>`,`<div style="flex: 2 1 220px; min-width: 0;">${cc({t:'Medium · labels thin out',body:bars(hires.filter((_,i)=>i%2===0),{h:120})})}</div>`,`<div style="flex: 1 1 140px; min-width: 0;">${cc({t:'Narrow · number only',v:'82',body:spark(hires.map(h=>h[1]).slice(0,9),{w:120,h:36})})}</div>`],{gap:12,align:'stretch'}),{wide:1}],
['Zoom, drag and right-click',R([`<div style="flex: 1 1 340px; min-width: 0;">${cc({t:'Headcount',v:'312',body:line([HEAD],{area:1,zoom:[6,10],labels:['Jan','Apr','Jul','Oct','Dec'],brush:[45,85]})})}</div>`,menu([{l:'Zoom to selection',icon:'zoom-in',kbd:'Z'},{l:'Reset zoom',icon:'scan',kbd:'0'},'-',{l:'Copy values',icon:'copy'},{l:'Download CSV',icon:'download'},{l:'Download PNG',icon:'image'}],{w:220})],{gap:12,align:'flex-start'}),{wide:1,note:M?'Pinch to zoom and drag to pan. Long-press opens the menu.':'Drag across the chart to zoom in, and double-click to reset. Right-click opens the menu, which also has a keyboard shortcut.'}]]});
S.push({g:'Charts',id:'bar',name:'Bar',desc:'Compare amounts. Vertical bars suit periods of time, and horizontal bars suit named categories.',stories:[
['Vertical: periods',cc({t:'Hires, 2026',v:'82',sub:'14 in September, the most so far',body:bars(hires,{hi:8,future:9})}),{wide:1}],
['With a target line',cc({t:'Hires per quarter vs target',v:'82 / 90',body:bars(qx.map((q,i)=>[q,[22,30,30,0][i]]),{target:25,targetLabel:'Target 25',warnBelow:1,future:3,bw:56})})],
['Horizontal: categories',cc({t:'Headcount by team',body:bars([['Engineering',124],['Sales',64],['Support',48],['Design',28],['Finance',26],['People',22]],{horizontal:1})})],
['Stacked and normalised',C([cc({t:'Hires by level',body:bars(qx.map((q,i)=>[q,[[8,10,4],[12,12,6],[10,14,6],[0,0,0]][i]]),{legend:['Junior','Mid','Senior'],bw:56})}),cc({t:'Gender by team, normalised',body:bars([['Engineering',[62,34,4]],['Design',[40,56,4]],['Sales',[52,46,2]]],{horizontal:1,norm:1,legend:['Men','Women','Non-binary']})})],{gap:12}),{wide:1}],
['Selectable bars',cc({t:'Leavers by month',v:'4',sub:'September · click a bar to filter the table',body:bars(MO.slice(0,9).map((m,i)=>[M?m[0]:m,LEAV[i]]),{sel:[8],valueOn:8})})]]});
S.push({g:'Charts',id:'trend',name:'Trend',desc:'How a value changes over time. The line is the data and the dashed line is the plan. Nothing else.',stories:[
['Playground',cc({t:'Headcount, last 12 months',v:'312',sub:'+18.6% year on year',body:line([HEAD],{area:1,endDot:1,labels:['Oct','Jan','Apr','Jul','Sep']})}),{wide:1}],
['Line or area',`<div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(min(100%, 260px), 1fr)); gap: 12px;">${cc({t:'Line · for comparing',body:line([HEAD],{h:120})})}${cc({t:'Area · for totals',body:line([HEAD],{h:120,area:1})})}</div>`,{wide:1}],
['Two series',cc({t:'Headcount vs plan',v:'312',body:line([HEAD,PLAN],{dash:[1],legend:['Actual','Plan'],labels:['Jan','Apr','Jul','Oct','Dec'],colors:['var(--r-chart-1)','var(--r-fg-3)']})}),{wide:1}],
['Small multiples',`<div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(min(100%, 160px), 1fr)); gap: 10px;">${smallMult.join('')}</div>`,{wide:1,note:'Same scale, same size, one per team. Easier to compare than four lines on one chart.'}],
['Sparklines',C([['Headcount',HEAD,'312','var(--r-success)'],['Attrition',[8.2,7.9,7.6,7.4,7.1,6.8,6.4,6.1],'6.1%','var(--r-success)'],['Open roles',[11,12,12,14,13,15,16,18],'18','var(--r-warning)']].map(([l,s,v,c],i,a)=>`<div style="display: flex; align-items: center; gap: 12px; padding: 10px 0;${i<a.length-1?' box-shadow: inset 0 -1px 0 var(--r-line);':''}"><span style="flex: 1; font: 500 ${M?16:14}px/1 var(--r-font);">${l}</span>${spark(s,{c,w:80,h:28})}<span style="width: 52px; text-align: right; font: 700 ${M?17:15}px/1 var(--r-font); font-variant-numeric: tabular-nums;">${v}</span></div>`))],
['Hover, click and legend toggles',cc({t:'Headcount by site',body:line([[80,84,88,92,96,99,104,108,110,114,118,121],[60,62,62,65,68,70,71,74,76,78,80,82],[40,41,44,46,47,49,52,54,55,57,58,60]],{hover:7,tip:'<b>August</b><br>Berlin 108 · London 74',off:[2],legend:['Berlin','London','Remote'],legendBtn:1,labels:['Jan','Apr','Jul','Oct','Dec']})}),{wide:1,note:'Click a legend item to hide that series. The hidden one is struck through, and the axis rescales.'}],
['Zoom and pan',cc({t:'Daily active users, 2026',right:R([btn('',{v:'secondary',size:'xs',icon:'zoom-out'}),btn('',{v:'secondary',size:'xs',icon:'zoom-in'}),btn('Reset',{v:'ghost',size:'xs'})],{gap:4}),body:line([Array.from({length:40},(_,i)=>180+Math.round(Math.sin(i/3)*18+i*2.2))],{area:1,labels:['1 Aug','15 Aug','1 Sep','15 Sep'],brush:[55,95]})}),{wide:1}]]});
S.push({g:'Charts',id:'distribution',name:'Distribution',desc:'Parts of a whole. Use it for up to six parts, and go biggest first.',stories:[
['Playground',cc({t:'Headcount by team',body:donut([['Engineering',124],['Sales',64],['Support',48],['Design',28],['Finance',26],['People',22]],{sub:'people'})})],
['When it stops working',`<div style="display: grid; grid-template-columns: ${M?'1fr':'1fr 1fr'}; gap: 12px;">${C([lbl('12 slices: unreadable'),donut(Array.from({length:12},(_,i)=>['L'+i,20-i]),{legend:false,size:130,colors:[...CH,...CH]})])}${C([lbl('Use a bar chart instead'),bars([['Berlin',98],['London',64],['Paris',38],['Madrid',30],['Other',82]],{horizontal:1})])}</div>`,{wide:1}],
['Sizes',R([donut([['A',60],['B',30],['C',10]],{size:64,legend:false,center:'60%'}),donut([['A',60],['B',30],['C',10]],{size:110,legend:false,center:'60%'}),donut([['A',60],['B',30],['C',10]],{size:160,legend:false,center:'60%',sub:'Permanent'}),donut([['A',72],['B',28]],{size:110,thin:1,legend:false,center:'72%'})],{gap:20,align:'center'})]]});
const hm=[[2,4,6,5,3,1,0],[3,6,9,8,5,2,1],[4,7,10,9,6,2,0],[3,6,8,7,5,1,0],[2,4,5,4,2,0,0]];
S.push({g:'Charts',id:'heatmap',name:'Heatmap',desc:'Intensity across two dimensions, such as when people take leave. Darker means more.',stories:[
['Playground',cc({t:'Leave requests by week and day',body:heat(hm,{rows:['W1','W2','W3','W4','W5'],cols:['M','T','W','T','F','S','S'],hiL:'10'})})],
['A fixed scale',`<div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(min(100%, 220px), 1fr)); gap: 12px;">${cc({t:'Engineering · max 10',body:heat(hm,{cols:['M','T','W','T','F','S','S'],max:10,hiL:'10',showV:1})})}${cc({t:'Sales · same scale',body:heat(hm.map(r=>r.map(v=>Math.round(v/2))),{cols:['M','T','W','T','F','S','S'],max:10,hiL:'10',showV:1})})}</div>`,{wide:1,note:'When you compare heatmaps, lock them to one scale. Otherwise the same colour means different numbers.'}],
['Tones',C(['accent','success','warning','danger'].map(t=>heat([[1,3,5,7,9,10,8,6,4,2,1,0]],{tone:t,scale:false,ar:1.4})),{gap:8})]]});
S.push({g:'Charts',id:'funnel',name:'Funnel',desc:'How many make it through each stage. Look at the drop between stages, not the stages themselves.',stories:[
['Playground',cc({t:'Hiring, Q3',v:'24 offers',body:funnel([['Applied',1240],['Screened',420],['Interviewed',96],['Offered',24],['Hired',19]])}),{wide:1}],
['Finding the bottleneck',cc({t:'Hiring, Q3',sub:'Only 23% of screened candidates get an interview',body:funnel([['Applied',1240],['Screened',420],['Interviewed',96],['Offered',24],['Hired',19]],{hi:2})}),{wide:1}],
['Comparing two funnels',`<div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(min(100%, 260px), 1fr)); gap: 12px;">${cc({t:'Referrals',v:'32% hired',body:funnel([['Applied',80],['Interview',46],['Hired',26]],{color:'var(--r-chart-2)'})})}${cc({t:'Job boards',v:'1% hired',body:funnel([['Applied',1160],['Interview',50],['Hired',12]],{color:'var(--r-chart-1)'})})}</div>`,{wide:1}],
['When it does not narrow',C([funnel([['Invited',120],['Started',96],['Completed',104]]),alert({tone:'warning',title:'More completed than started',body:'Some people finished without a "started" event. Check the tracking before you trust these numbers.'})],{gap:12})]]});
S.push({g:'Charts',id:'chart-timeline',name:'Timeline (Gantt)',desc:'Who is doing what, and when. Lanes are people or projects, and bars are periods of time.',stories:[
['Playground',gantt({cols:days,lanes:cover,today:2,off:[5,6]}),{wide:1}],
['Shapes',gantt({cols:MO.slice(8,12).concat(['Jan']),lanes:[{l:'Bar',items:[{s:0,e:2.5,l:'Payroll migration'}]},{l:'Pill',items:[{s:1,e:3,l:'Hiring freeze',pill:1,t:'warning'}]},{l:'Milestone',items:[{s:2.4,ms:1,l:'Go live',t:'success'}]},{l:'Tentative',items:[{s:3,e:4.6,l:'Q1 plan',ghost:1}]}]}),{wide:1}],
['Day, week, month',C([seg(['Day','Week','Month'],1,{size:'sm'}),gantt({cols:['W40','W41','W42','W43','W44','W45'],lanes:[{l:'Onboarding',items:[{s:0,e:2,l:'Lucas',t:'accent'}]},{l:'Reviews',items:[{s:1,e:4,l:'Mid-year',t:'info'}]},{l:'Payroll',items:[{s:3.8,ms:1,l:'Run'}]}],today:1})],{gap:10}),{wide:1}],
['Zoom, drag and select',gantt({cols:days,lanes:cover,sel:[2,5],off:[5,6]}),{wide:1,note:'Drag across empty days to select a range, then create leave or cover for those days.'}],
['Leave cover',gantt({cols:days,lanes:[{l:'Design team',dot:'var(--r-chart-2)',items:[{s:0,e:12,l:'Needs 2 people in',t:'neutral',ghost:1}]},{l:'Amara Okafor',av:1,items:[{s:0,e:5,l:'Vacation',t:'info'}]},{l:'Hana Kim',av:1,items:[{s:2,e:4,l:'Sick',t:'danger'}]},{l:'Cover gap',items:[{s:2,e:4,l:'Only 1 in',t:'danger',solid:1}]}],off:[5,6]}),{wide:1}],
['Nothing scheduled',box(empty({icon:'calendar',title:'Nothing scheduled this week',body:'Leave, training and on-call shifts will show up here.',acts:btn('Add an entry',{v:'secondary',size:'sm',icon:'plus'}),pad:10}))],
['When items collide',gantt({cols:days,lanes:[{l:'Priya Shah',av:1,h:M?72:66,items:[{s:0,e:4,l:'Vacation',t:'info',row:0},{s:2,e:3,l:'On call',t:'warning',row:1,clash:1},{s:6,e:9,l:'Training',t:'accent',row:0}]},{l:'Omar Haddad',av:1,items:[{s:3,e:6,l:'Conference',t:'accent'}]}]}),{wide:1,note:'Overlapping items stack into rows. A real conflict gets a red outline.'}],
['Drag to reschedule',gantt({cols:days,lanes:[{l:'Priya Shah',av:1,items:[{s:7,e:12,l:'Vacation',t:'info',dim:1,ghost:1},{s:8,e:12,l:'Vacation · 8–12',t:'info',drag:1}]},{l:'Yuki Sato',av:1,items:[{s:4,e:5,l:'Training',t:'accent'}]}],off:[5,6]}),{wide:1}],
['Telling lanes apart',gantt({cols:days,stripe:1,lanes:[{l:'Engineering',dot:'var(--r-chart-1)',items:[{s:0,e:3,l:'Sprint 42',t:'accent'}]},{l:'Design',dot:'var(--r-chart-2)',items:[{s:1,e:5,l:'Research',t:'success'}]},{l:'Sales',dot:'var(--r-chart-3)',items:[{s:3,e:8,l:'Kick-off',t:'warning'}]},{l:'Support',dot:'var(--r-chart-4)',items:[{s:6,e:11,l:'Rota',t:'danger'}]}]}),{wide:1}]]});
const srch=`<div style="position: absolute; left: 12px; top: 12px; right: 12px; display: flex; gap: 8px; align-items: center; z-index: 2;"><div style="flex: 0 1 280px;">${field({pre:'i:search',value:'Mei',size:'sm',state:'focus'})}</div><span style="font: 500 12px/1 var(--r-font); color: var(--r-fg-2); background: var(--r-surface); padding: 6px 10px; border-radius: 999px; box-shadow: var(--r-shadow-1);">1 match</span></div>`;
S.push({g:'Charts',id:'org-chart',name:'Org chart',desc:M?'On a phone the org chart is a tree you expand and collapse. Tap a person to open their profile, and use "View as chart" for the full canvas.':'Who reports to whom. Pan and zoom the canvas, search to focus on someone, and drag to change a reporting line if you have permission.',stories:[
['Playground',oc(tr()),{wide:1}],
['Pan and zoom',oc(tr(),{scale:M?1:0.6,mini:!M,tree:0}),{wide:1,note:M?'Pinch the canvas view to zoom.':'Scroll or pinch to zoom, and drag empty space to pan. The minimap shows where you are.'}],
['Search, focus and the chain',oc(tr((n,d,p)=>{if(n.n==='Mei Tanaka'){n.match=1;n.chain=1;}if(n.n==='Zara Ahmed'||n.n==='Nora Becker')n.chain=1;if(!n.chain&&n.n!=='Mei Tanaka')n.dim=1;}),{top:M?'':srch}),{wide:1,note:'Search dims everyone else and highlights the chain of managers up to the top.'}],
['Read-only for everyone else',C([alert({tone:'info',icon:'eye',title:'You\u2019re viewing, not editing',body:'Only People admins can change reporting lines.'}),oc(tr(),{h:M?undefined:360,scale:M?1:0.7})],{gap:10}),{wide:1}],
['Nothing moves under the pointer',oc(tr((n)=>{if(n.n==='Omar Haddad')n.sel=1;}),{h:M?undefined:380}),{wide:1,note:'Opening or closing a branch keeps the card you clicked exactly where it is. The rest of the chart shifts around it.'}],
['Drag to change a reporting line',oc(tr((n)=>{if(n.n==='Tom Fischer')n.drop=1;if(n.n==='Mei Tanaka')n.drag=1;}),{h:M?undefined:380}),{wide:1,note:'Drop Mei on Tom to make him her manager. We ask you to confirm first, and the change takes effect from a date you choose.'}],
['Driving something else',R([`<div style="flex: 2 1 400px; min-width: 0;">${oc(tr((n)=>{if(n.n==='Jonas Weber')n.sel=1;}),{h:M?undefined:360,scale:M?1:0.6})}</div>`,`<div style="flex: 1 1 240px; min-width: 0;">${box(C([L.pc({n:'Jonas Weber',r:'CTO · 3 reports'},{s:44}),kv([['Team','Engineering'],['Span','3 direct, 3 total'],['Open roles','1']],{stack:1}),btn('Open profile',{v:'secondary',full:1,size:'sm'})],{gap:12}))}</div>`],{gap:12,align:'flex-start'}),{wide:1}],
['Vertical and horizontal',M?C([oc(tr()),note('On a phone both directions become the indented list.')]):C([seg(['Top down','Left to right'],1,{size:'sm'}),orgCanvas(orgLR(tr((n)=>{if(n.n==='Jonas Weber'||n.n==='Tom Fischer')n.collapsed=1;})),{h:340,scale:0.8,left:1})],{gap:10}),{wide:1}],
['Selecting a person',oc(tr((n)=>{if(n.n==='Priya Shah')n.sel=1;}),{h:M?undefined:380}),{wide:1,note:'Click or press Enter to select. The arrow keys move up, down and along the tree.'}],
['Custom cards',M?oc(tr()):orgCanvas(orgTD({n:'Jonas Weber',r:'CTO',x:badge('3 reports',{size:'sm'}),k:[{n:'Priya Shah',r:'Senior Engineer',x:`${badge('On call',{tone:'warning',size:'sm'})}`},{n:'Omar Haddad',r:'Backend Engineer',x:`${badge('New',{tone:'accent',size:'sm'})}`},{n:'Yuki Sato',r:'iOS Engineer',x:`${badge('Tokyo',{size:'sm'})}`}]},{custom:1}),{h:300,scale:0.85}),{wide:1}],
['A circular reporting line',C([alert({tone:'danger',title:'This would create a loop',body:'Jonas reports to Nora. Nora can\u2019t report to Priya, because Priya reports to Jonas.'}),M?oc(tr((n)=>{if(['Nora Becker','Jonas Weber','Priya Shah'].includes(n.n))n.match=1;})):orgCanvas(orgTD({n:'Nora Becker',r:'Chief Executive',warn:1,k:[{n:'Jonas Weber',r:'CTO',warn:1,k:[{n:'Priya Shah',r:'Senior Engineer',warn:1}]}]}),{h:300,scale:0.85,controls:false})],{gap:10}),{wide:1}]]});
S.push({g:'Charts',id:'movement',name:'Movement',desc:'How a number got from start to end. Green adds, red takes away, and indigo is a total.',stories:[
['Playground',cc({t:'Headcount, Q3',v:'297 → 312',body:waterfall([['1 Jul',297,'total'],['Hires',32],['Transfers in',4],['Leavers',-14],['Transfers out',-7],['30 Sep',312,'total']])}),{wide:1}],
['Reading the biggest step',cc({t:'Headcount, Q3',sub:'Hiring drove the growth: 32 people',body:waterfall([['1 Jul',297,'total'],['Hires',32],['Transfers in',4],['Leavers',-14],['Transfers out',-7],['30 Sep',312,'total']],{hi:1})}),{wide:1}],
['When it goes negative',cc({t:'Budget vs spend, €k',v:'−€18k',body:waterfall([['Budget',40,'total'],['Salaries',-38],['Contractors',-14],['Refunds',4],['Balance',-8,'total']])}),{wide:1,note:'Below zero, the axis line becomes the reference, so the bars hang under it.'}]]});
const bandRows=[{l:'Engineer L2',min:62,max:82,mid:72,q:[67,77],p:[64,70,74,79]},{l:'Engineer L3',min:78,max:102,mid:90,q:[84,96],p:[82,88,92,101,105]},{l:'Designer L3',min:70,max:92,mid:81,q:[75,87],p:[72,84,68]},{l:'Manager L4',min:100,max:130,mid:115,q:[107,123],p:[112,118]}];
S.push({g:'Charts',id:'pay',name:'Pay',desc:'Salary bands and fairness. These charts are sensitive, so they only show to people who can see pay.',stories:[
['Salary bands',cc({t:'Bands by level, €k',right:badge('HR only',{icon:'lock',size:'sm'}),body:bands(bandRows.map(r=>({l:r.l,min:r.min,max:r.max})),{lo:55,hi:135,ticks:['55','75','95','115','135']})}),{wide:1}],
['Out of band',cc({t:'People by band, €k',sub:'2 people outside their band',body:bands(bandRows.map(r=>({l:r.l,min:r.min,max:r.max,p:r.p})),{lo:55,hi:135,ticks:['55','75','95','115','135']})}),{wide:1}],
['Median and middle half',cc({t:'Median and interquartile range, €k',body:bands(bandRows,{lo:55,hi:135,ticks:['55','75','95','115','135']})+legend(['Band','Middle half','Median'],['var(--r-accent-soft-hover)','color-mix(in oklch, var(--r-accent) 45%, transparent)','var(--r-fg)'])}),{wide:1}],
['Pay equity scatter',cc({t:'Salary vs level, by gender',sub:'Women earn 2.1% less at the same level (adjusted)',body:scatter([[1,64,0],[1,66,1],[1,70,0],[1,63,1],[2,78,0],[2,76,1],[2,82,0],[2,80,1],[3,90,0],[3,87,1],[3,96,0],[3,92,1],[4,112,0],[4,108,1],[4,120,0],[5,132,0],[5,128,1]].map(([x,y,g])=>({x:x+(g?0.12:-0.12),y,g})),{x0:0.5,x1:5.5,y0:55,y1:140,fit:[[8,86],[5,82]],xl:['L1','L2','L3','L4','L5'],legend:['Men','Women']})}),{wide:1}]]});
return S;}
