import type { NewFieldsView } from './new-information';

/** A file with four columns that match no field: what People proposes for them. */
const counts = { fromFile: 128, existingWithout: 342 };
const own = { ownership: ['employee'], visibility: ['self', 'hr'] } as const;

export const NEW_FIELDS: NewFieldsView = {
  canCreate: true,
  blocked: null,
  byModel: true,
  existingPeople: 470,
  summary: 'Adds 4 fields.',
  sections: [
    { key: 'personal', label: 'Personal information' },
    { key: 'employment', label: 'Employment' },
  ],
  proposals: [
    {
      column: 3,
      header: 'Emergency contact',
      shape: 'free text, up to 24 characters',
      include: true,
      key: 'emergency_contact',
      field: {
        label: 'Emergency contact',
        dataType: 'text',
        required: false,
        ...own,
        classification: 'confidential',
        piiKind: 'contact',
        encrypted: false,
        aiEligible: false,
      },
      placement: { newSection: 'Emergency contact' },
      why: 'Contact details are personal: the employee keeps them up to date, HR can see them.',
      forExisting: { kind: 'ask' },
      forExistingWhy: 'Only they know it: they are asked, and reminded until it is filled in.',
      counts,
      sensitive: null,
    },
    {
      column: 4,
      header: 'Cost centre',
      shape: '2 letters + other + 2 digits',
      include: true,
      key: 'cost_centre',
      field: {
        label: 'Cost centre',
        dataType: 'text',
        required: false,
        ownership: ['hr'],
        visibility: ['self', 'manager', 'hr'],
        classification: 'internal',
        piiKind: 'none',
        encrypted: false,
        aiEligible: true,
      },
      placement: { sectionKey: 'employment' },
      why: 'Organisational data HR keeps; managers can see it for their team.',
      forExisting: { kind: 'hr' },
      forExistingWhy: 'HR records it: it goes to HR’s completeness list.',
      counts,
      sensitive: null,
    },
    {
      column: 5,
      header: 'T-shirt size',
      shape: '4 distinct short values',
      include: true,
      key: 't_shirt_size',
      field: {
        label: 'T-shirt size',
        dataType: 'select',
        options: ['S', 'M', 'L', 'XL'],
        required: false,
        ...own,
        classification: 'internal',
        piiKind: 'none',
        encrypted: false,
        aiEligible: true,
      },
      placement: { newSection: 'Equipment' },
      why: 'Ordinary, not sensitive: the employee fills it in, and the assistant may use it.',
      forExisting: { kind: 'leave' },
      forExistingWhy: 'Nice to have: nobody is chased for it.',
      counts,
      sensitive: null,
    },
    {
      column: 6,
      header: 'IBAN',
      shape: 'IBAN-like, country ES',
      include: true,
      key: 'iban',
      field: {
        label: 'IBAN',
        dataType: 'bank_account',
        country: 'ES',
        required: false,
        ...own,
        classification: 'confidential',
        piiKind: 'financial',
        encrypted: true,
        aiEligible: false,
      },
      placement: { newSection: 'Bank and pay' },
      why: 'Bank and pay details are financial: sealed, seen by the employee and HR, never by the assistant.',
      forExisting: { kind: 'ask' },
      forExistingWhy: 'Only they know it: they are asked, and reminded until it is filled in.',
      counts,
      sensitive: 'Financial',
    },
  ],
};
