import { readFile } from 'node:fs/promises';
import { describe, expect, it } from 'vitest';
import { ok } from '@kithena/domain-kit';

import type { Caller } from '../application/ports.js';
import { caller, people, world } from '../application/testing/world.js';
import { timeoffServer } from '../http/server.js';

/**
 * TOF-044: the subgraph's SDL is the committed one, and its fields reach
 * REST's routes as the request's caller.
 */

function boot() {
  const app = world('2026-10-01T07:00:00.000Z', { withGrant: true });
  const server = timeoffServer({
    ...app.deps,
    callerFrom: (request) => ok(caller(String(request.headers['x-as']) as Caller['personId'])),
  });
  return async (as: string, query: string) => {
    const response = await server.graphql.fetch('http://timeoff.test/graphql', {
      method: 'POST',
      headers: { 'content-type': 'application/json', 'x-as': as },
      body: JSON.stringify({ query }),
    });
    return (await response.json()) as {
      data?: Record<string, unknown>;
      errors?: { message: string; extensions?: { code?: string } }[];
    };
  };
}

describe('the subgraph', () => {
  it('prints the SDL committed in schemas/timeoff.graphql', async () => {
    const graphql = boot();
    const answer = await graphql(people.adam, '{ _service { sdl } }');
    const committed = await readFile(
      new URL('../../schemas/timeoff.graphql', import.meta.url),
      'utf8',
    );
    const sdl = (answer.data?.['_service'] as { sdl: string } | undefined)?.sdl.trim() ?? '';
    // Regenerate with `pnpm --filter @kithena/timeoff codegen` when this fails.
    expect(`# Generated by @kithena/codegen. Do not edit.\n\n${sdl}\n`).toBe(committed);
  });

  it('answers a screen whole, and maps a refusal to the domain’s code', async () => {
    const graphql = boot();
    const overview = await graphql(
      people.adam,
      '{ timeOffOverview { member { displayName } balances { leaveTypeKey left yearly } } }',
    );
    expect(overview.errors).toBeUndefined();
    expect(overview.data?.['timeOffOverview']).toEqual({
      member: { displayName: 'Adam Novak' },
      balances: [{ leaveTypeKey: 'vacation', left: '25.000', yearly: '25.000' }],
    });
    const settings = await graphql(
      people.adam,
      '{ timeOffLeaveTypeSettings { leaveTypes { hidden } } }',
    );
    expect(settings.errors?.[0]?.extensions?.code).toBe('FORBIDDEN');
  });

  it('adds balances to Person for the person and their manager, and null for a teammate', async () => {
    const graphql = boot();
    const query = `{ _entities(representations: [{ __typename: "Person", id: "${people.adam}" }]) {
      ... on Person { timeOffBalances { left } } } }`;
    const own = await graphql(people.adam, query);
    expect(own.data?.['_entities']).toEqual([{ timeOffBalances: [{ left: '25.000' }] }]);
    const manager = await graphql(people.marco, query);
    expect(manager.data?.['_entities']).toEqual([{ timeOffBalances: [{ left: '25.000' }] }]);
    const teammate = await graphql(people.omar, query);
    expect(teammate.data?.['_entities']).toEqual([{ timeOffBalances: null }]);
  });
});
