/**
 * Emits a module's federated SDL to `schemas/<module>.graphql`.
 *
 * The gateway composes the supergraph from these files and `wgc subgraph check`
 * diffs them, so a change that would break a composed field fails in CI rather
 * than at deploy. Run from a module directory:
 *
 *   pnpm --filter @hris/timeoff codegen
 *
 * The file is generated. Edit the Pothos schema, never the SDL.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { basename, join } from 'node:path';

import { graphql, GraphQLSchema } from 'graphql';

/**
 * The SDL is read from the schema's own `_service { sdl }` field rather than
 * printed locally.
 *
 * That field is what a federation router actually fetches, and it is the only
 * rendering that carries `@key` and the `@link` correctly: Pothos keeps the
 * federation directives as extensions, which `printSchema` drops silently and
 * `printSchemaWithDirectives` mangles into `@0(name: "key", …)`. Either way the
 * supergraph composes having forgotten what an entity is — and it composes
 * *successfully*, which is the dangerous part.
 */
async function subgraphSdl(schema: GraphQLSchema, moduleName: string): Promise<string> {
  const result = await graphql({ schema, source: '{ _service { sdl } }' });

  if (result.errors?.length) {
    throw new Error(`${moduleName}: ${result.errors.map((e) => e.message).join('; ')}`);
  }

  const sdl = readServiceSdl(result.data);
  if (!sdl) {
    throw new Error(
      `${moduleName}: the schema exposes no _service.sdl. Was it built with builder.toSubGraphSchema()?`,
    );
  }
  return sdl.trim();
}

/** True for any non-null object, the precondition for reading a property off it. */
function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}

/**
 * The federation SDL out of an executed `_service { sdl }` query.
 *
 * A GraphQL response is `unknown` as far as the type system is concerned, and
 * asserting a shape onto it means a server that answers differently produces
 * `undefined` several frames later rather than failing here. Walking it with
 * checks turns that into the explicit error below.
 */
function readServiceSdl(data: unknown): string | undefined {
  if (!isRecord(data)) return undefined;
  const service = data['_service'];
  if (!isRecord(service)) return undefined;
  const sdl = service['sdl'];
  return typeof sdl === 'string' ? sdl : undefined;
}

/** The `schema` export of a dynamically imported module. */
function readSchemaExport(mod: unknown): GraphQLSchema | undefined {
  if (!isRecord(mod)) return undefined;
  const schema = mod['schema'];
  // `instanceof` rather than a shape assertion: a module that exports something
  // else named `schema` is the case this has to catch, and only the real class
  // can answer that.
  return schema instanceof GraphQLSchema ? schema : undefined;
}

async function main(): Promise<void> {
  const moduleDir = process.cwd();
  const moduleName = basename(moduleDir);

  const mod: unknown = await import(join(moduleDir, 'src/graphql/schema.ts'));
  const schema = readSchemaExport(mod);
  if (!schema) {
    throw new Error(`${moduleName}: src/graphql/schema.ts must export \`schema\`.`);
  }

  const outputDir = join(moduleDir, 'schemas');
  await mkdir(outputDir, { recursive: true });

  const target = join(outputDir, `${moduleName}.graphql`);
  const sdl = await subgraphSdl(schema, moduleName);
  await writeFile(target, `# Generated by @hris/codegen. Do not edit.\n\n${sdl}\n`, 'utf8');

  console.log(`${moduleName}: wrote ${target}`);
}

await main();
