import { mkdirSync, readdirSync, readFileSync, rmSync, statSync, watch, writeFileSync } from 'node:fs';
import { basename, dirname, join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

import { storyNameFromExport } from 'storybook/internal/csf';

/**
 * Every story as a folder holding two stories: Web and Mobile.
 *
 * Rendering both views inside one story put two copies of the component on the
 * canvas, so every event either copy fired landed in one Actions log and the
 * panels could not say which one it came from. Two real stories give each view
 * its own canvas, its own Actions, Interactions and Controls, and its own URL.
 *
 * The stories are written by Reach next to its components and are not
 * repeated there. This writes a thin CSF file per story into
 * `apps/storybook/generated/views` that imports the original and re-exports it
 * twice with a `view` parameter, which `withViews` in `preview.tsx` reads. The
 * originals stay indexed for the component's Overview page and the test runs,
 * and are tagged out of the sidebar; the generated ones are tagged out of docs
 * and tests, so nothing renders or runs twice.
 *
 * Runs when Storybook loads its config (dev, build and the Vitest plugin all
 * do), and in dev keeps the folder in step as stories are added or renamed.
 */

const here = dirname(fileURLToPath(import.meta.url));
const SOURCE = join(here, '../../../packages/ui/src');
const OUT = join(here, '../generated/views');

/** Mirrors the extglob in `main.ts`: the other product's mark is never published here. */
const EXCLUDED = /(^|\/)kithena\.stories\.tsx$/;

function storyFiles(dir: string): string[] {
  const found: string[] = [];
  for (const entry of readdirSync(dir)) {
    const path = join(dir, entry);
    if (statSync(path).isDirectory()) found.push(...storyFiles(path));
    else if (/\.stories\.tsx?$/.test(entry) && !EXCLUDED.test(path)) found.push(path);
  }
  return found;
}

/** A title segment may not contain `/`, which Storybook reads as nesting. */
const segment = (name: string): string => name.replaceAll('/', '∕');
const literal = (value: string): string => JSON.stringify(value);

function viewsFor(file: string): Map<string, string> {
  const source = readFileSync(file, 'utf8');
  const title = /^\s*title:\s*'([^']+)'/m.exec(source)?.[1];
  const out = new Map<string, string>();
  if (title === undefined) return out;

  const exports = [...source.matchAll(/^export const (\w+)\b[^=]*=/gm)];

  exports.forEach((match, index) => {
    const exportName = match[1];
    if (exportName === undefined) return;
    const block = source.slice(match.index, exports[index + 1]?.index ?? source.length);
    const name = /^ {2}name:\s*'([^']+)'/m.exec(block)?.[1] ?? storyNameFromExport(exportName);
    const relativeDir = relative(SOURCE, dirname(file));
    // Numbered so the folders keep the order the stories were written in:
    // the sidebar lists them in the order it finds the files.
    const order = String(index + 1).padStart(2, '0');
    const target = join(
      OUT,
      relativeDir,
      `${relativeFileStem(file)}.${order}-${exportName}.stories.ts`,
    );
    const importFrom = relative(dirname(target), file)
      .split(sep)
      .join('/')
      .replace(/\.tsx?$/, '');
    out.set(
      target,
      `// Generated by apps/storybook/.storybook/story-views.ts. Do not edit.\n` +
        `import meta, { ${exportName} as story } from ${literal(importFrom)};\n\n` +
        `export default {\n` +
        `  ...meta,\n` +
        `  title: ${literal(`${title}/${segment(name)}`)},\n` +
        `  tags: ['dev', '!autodocs', '!test'],\n` +
        `};\n\n` +
        `export const Web = { ...story, name: 'Web', parameters: { ...story.parameters, view: 'web' } };\n` +
        `export const Mobile = { ...story, name: 'Mobile', parameters: { ...story.parameters, view: 'mobile' } };\n`,
    );
  });
  return out;
}

function relativeFileStem(file: string): string {
  return basename(file).replace(/\.stories\.tsx?$/, '');
}

function existing(dir: string): string[] {
  try {
    return readdirSync(dir).flatMap((entry) => {
      const path = join(dir, entry);
      return statSync(path).isDirectory() ? existing(path) : [path];
    });
  } catch {
    return [];
  }
}

/** Writes only what changed, so a save in one story does not reload every other. */
export function generateStoryViews(): void {
  const wanted = new Map<string, string>();
  for (const file of storyFiles(SOURCE)) {
    for (const [target, content] of viewsFor(file)) wanted.set(target, content);
  }
  for (const stale of existing(OUT)) {
    if (!wanted.has(stale)) rmSync(stale);
  }
  for (const [target, content] of wanted) {
    let current: string | undefined;
    try {
      current = readFileSync(target, 'utf8');
    } catch {
      current = undefined;
    }
    if (current === content) continue;
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, content);
  }
}

/** Regenerates when a story file changes. `unref` so a build still exits. */
export function watchStoryViews(): void {
  let pending: ReturnType<typeof setTimeout> | undefined;
  const watcher = watch(SOURCE, { recursive: true }, (_event, file) => {
    if (file === null || !/\.stories\.tsx?$/.test(file)) return;
    clearTimeout(pending);
    pending = setTimeout(generateStoryViews, 150);
  });
  watcher.unref();
}
