import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';

import * as contracts from '@kithena/contracts';

/*
 * The outbox relay routes each row by its `topic` column, which Postgres
 * derives from the event's name and version (`*_outbox_relay.sql`)
 * because Debezium can route by one column only. That is a second derivation of
 * what `defineEvent` names, in another language; this is what keeps them the
 * same. If an event's topic stops matching the SQL, its events go to a topic
 * nobody reads.
 */
const SQL = `'${contracts.EVENT_NAMESPACE}.' || split_part(event_name, '.', 1) || '.v' || event_version`;
const inSql = (name: string, version: number): string =>
  `${contracts.EVENT_NAMESPACE}.${name.split('.')[0] ?? ''}.v${String(version)}`;

const events = Object.values(contracts as Record<string, unknown>).filter(
  (value): value is { name: string; version: number; topic: string } =>
    typeof value === 'object' &&
    value !== null &&
    'topic' in value &&
    'name' in value &&
    'version' in value,
);

describe('the outbox topic column', () => {
  it('is generated by the expression this test mirrors, on both outboxes', () => {
    for (const file of [
      '20260927230000_outbox_relay.sql',
      '20260927230100_people_outbox_relay.sql',
    ]) {
      const migration = readFileSync(
        new URL(`../../../migrations/${file}`, import.meta.url),
        'utf8',
      );
      expect(migration.split(SQL)).toHaveLength(2);
    }
  });

  it('names the topic every event contract names', () => {
    expect(events.length).toBeGreaterThan(20);
    for (const event of events) expect(inSql(event.name, event.version)).toBe(event.topic);
  });
});
