/**
 * Promote a tenant-defined attribute to a generated column, as a migration
 * file somebody reads before it runs.
 *
 * A directory over 50,000 people filtering on `custom->>'employee_grade'` is a
 * sequential scan with a JSONB extraction per row. The fix is a generated
 * column with its own index — and the reason that fix is a *file* rather than
 * something a settings screen does is the rule this repository already has:
 * migrations are expand-contract and reviewed. `ALTER TABLE` against a
 * multi-tenant production table takes a lock every other customer's reads
 * queue behind, and doing that at the moment an administrator ticks a box is
 * an outage with a settings screen in front of it.
 *
 * So this writes SQL to stdout or to `migrations/`. It opens no connection,
 * reads no registry and applies nothing. What it emits goes through review,
 * `atlas migrate hash`, and CI, like every other schema change.
 *
 * Usage:
 *
 *     pnpm --filter @kithena/scripts promote-attribute employee_grade text
 *     pnpm --filter @kithena/scripts promote-attribute salary_band text --write
 */

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

/** Postgres refuses an identifier over 63 bytes, silently truncating before that. */
const IDENTIFIER_MAX = 63;

const KEY_SHAPE = /^[a-z][a-z0-9_]*$/u;

/**
 * Which data types are worth promoting, and what each becomes.
 *
 * Deliberately not the whole catalogue. A promotion exists to make a filter or
 * a sort fast, and the types left out are the ones no directory filters on:
 * an address is a JSONB object, a document reference is a pointer, and a
 * repeating group has no single value to index. Promoting one of those would
 * produce a column that is either always null or an error at `ALTER TABLE`.
 */
const PROMOTABLE = {
  text: 'text',
  long_text: 'text',
  email: 'text',
  phone: 'text',
  url: 'text',
  country: 'text',
  currency: 'text',
  language: 'text',
  time_zone: 'text',
  select: 'text',
  national_id: 'text',
  number: 'bigint',
  decimal: 'numeric',
  percentage: 'numeric',
  boolean: 'boolean',
  date: 'date',
  datetime: 'timestamptz',
} as const;

export type PromotableType = keyof typeof PROMOTABLE;

export interface PromotionRequest {
  readonly attributeKey: string;
  readonly dataType: PromotableType;
  /** Stamped into the file name. Passed in so the output is reproducible in a test. */
  readonly at?: Date;
}

export interface Promotion {
  readonly fileName: string;
  readonly sql: string;
}

export class PromotionRefused extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'PromotionRefused';
  }
}

/**
 * The migration, as text.
 *
 * Separated from the CLI so it can be tested by applying the SQL to a real
 * database rather than by comparing it to a string somebody typed twice.
 */
export function promotionFor(request: PromotionRequest): Promotion {
  const { attributeKey, dataType } = request;

  if (!KEY_SHAPE.test(attributeKey)) {
    throw new PromotionRefused(
      `${attributeKey} is not an attribute key: lowercase letters, digits and underscores, starting with a letter`,
    );
  }

  const sqlType = PROMOTABLE[dataType] as string | undefined;
  if (sqlType === undefined) {
    throw new PromotionRefused(
      `${dataType} attributes are not worth promoting — nothing filters a directory on one`,
    );
  }

  const column = `custom_${attributeKey}`;
  const index = `person_${column}_idx`;
  for (const identifier of [column, index]) {
    if (identifier.length > IDENTIFIER_MAX) {
      throw new PromotionRefused(
        `${identifier} is ${String(identifier.length)} characters; Postgres truncates past ${String(IDENTIFIER_MAX)}`,
      );
    }
  }

  const stamp = (request.at ?? new Date()).toISOString().replaceAll(/[-:T]/gu, '').slice(0, 14);

  /*
   * `->>` then a cast, rather than a typed accessor.
   *
   * The cast is what makes a numeric filter use the index instead of comparing
   * text, and it is also the check: if any tenant has a non-numeric string
   * under this key, `ALTER TABLE` fails and the migration does not apply. That
   * is the right failure — loud, before deployment, naming the column — rather
   * than a column that is silently null for the rows that needed it most.
   */
  const expression =
    sqlType === 'text'
      ? `(custom ->> '${attributeKey}')`
      : `((custom ->> '${attributeKey}')::${sqlType})`;

  const sql = `-- Promote \`${attributeKey}\` to a generated column.
--
-- Generated by \`pnpm --filter @kithena/scripts promote-attribute\`. Read it
-- before it runs: this is a schema change to \`people.person\`, which every
-- tenant shares, and it is here as a file precisely so it goes through review
-- and CI rather than happening when somebody ticks a box.
--
-- Additive, per the expand-contract rule: a generated column derives from
-- \`custom\` and stores nothing new, so nothing has to be backfilled and
-- nothing stops working if this is rolled forward ahead of the code that
-- reads it.
--
-- ### What can go wrong, and where it will
--
-- If any row holds a value under \`${attributeKey}\` that cannot be cast to
-- \`${sqlType}\`, this statement fails and the migration does not apply. That is
-- the intended failure: it names the column, happens before deployment, and is
-- fixed by correcting the data or by not promoting this attribute. A column
-- that silently read null for those rows would be worse — the directory would
-- quietly stop finding exactly the people whose data was wrong.
--
-- ### Locking
--
-- \`ADD COLUMN ... GENERATED ALWAYS AS ... STORED\` rewrites the table and holds
-- an ACCESS EXCLUSIVE lock while it does. On a large \`people.person\` that is
-- minutes, not milliseconds. Schedule it accordingly.

ALTER TABLE people.person
  ADD COLUMN ${column} ${sqlType}
  GENERATED ALWAYS AS ${expression} STORED;

-- Tenant first: every directory query is already scoped to one, so a
-- tenant-leading index serves both the filter and the isolation.
CREATE INDEX ${index} ON people.person (tenant_id, ${column});

COMMENT ON COLUMN people.person.${column} IS
  'Generated from custom->>''${attributeKey}''. Promoted for directory filtering; the value is still written to custom.';
`;

  return { fileName: `${stamp}_promote_${attributeKey}.sql`, sql };
}

/** Where a written migration lands, relative to this file. */
export function migrationsDirectory(): string {
  return join(fileURLToPath(new URL('../../../migrations/', import.meta.url)));
}

function main(argv: readonly string[]): void {
  const [attributeKey, dataType, ...rest] = argv;

  if (attributeKey === undefined || dataType === undefined) {
    process.stderr.write(
      'usage: promote-attribute <attribute_key> <data_type> [--write]\n' +
        `data types: ${Object.keys(PROMOTABLE).join(', ')}\n`,
    );
    process.exitCode = 2;
    return;
  }

  let promotion: Promotion;
  try {
    promotion = promotionFor({ attributeKey, dataType: dataType as PromotableType });
  } catch (cause) {
    process.stderr.write(`${cause instanceof Error ? cause.message : String(cause)}\n`);
    process.exitCode = 1;
    return;
  }

  // Printing is the default and writing is the flag, because the safe thing to
  // do with a schema change is look at it.
  if (!rest.includes('--write')) {
    process.stdout.write(promotion.sql);
    process.stderr.write(
      `\n-- not written. Re-run with --write to place it in migrations/${promotion.fileName}\n`,
    );
    return;
  }

  const path = join(migrationsDirectory(), promotion.fileName);
  writeFileSync(path, promotion.sql, { flag: 'wx' });
  process.stdout.write(
    `${path}\n\nRun \`atlas migrate hash --dir file://migrations\` and commit both.\n`,
  );
}

// `import.meta.main` is Node 24's answer to the `require.main === module`
// dance, and it is what keeps this file importable by a test without running.
if (import.meta.main) main(process.argv.slice(2));
